import type {PropertyContent} from './types'

/** Objects 6–10: Plepa terrace 2+1, central Durres 1+1, Plazh 2+1+2, Plazh 1+1 67 m², Mali i Robit 42 m². */
export const BATCH_2: PropertyContent[] = [
  {
    datoId: 'WddpFV1MSKiuRuInaxW4sA',
    slug: 'prodazha-vidovoj-kvartiry-21-s-terassoj',
    city: 'durres',
    district: 'plepa-durres',
    type: 'apartment',
    status: 'sale',
    price: 180000,
    area: 108,
    bedrooms: 2,
    bathrooms: 1,
    title: {
      en: 'Two-Bedroom Apartment with a 41 m² Sea-View Terrace — Plepa, Durres',
      ru: 'Квартира 2+1 с террасой 41 м² и видом на море — Плепа, Дуррес',
      uk: 'Квартира 2+1 із терасою 41 м² та видом на море — Плепа, Дуррес',
      sq: 'Apartament 2+1 me tarracë 41 m² dhe pamje nga deti — Plepa, Durrës',
      it: 'Appartamento 2+1 con terrazza di 41 m² vista mare — Plepa, Durazzo',
      pl: 'Mieszkanie 2+1 z tarasem 41 m² i widokiem na morze — Plepa, Durres',
    },
    shortDescription: {
      en: 'Two-bedroom apartment in the Rotonda complex with a 41 m² private terrace and sea views from every window, 250 metres from the water.',
      ru: 'Квартира 2+1 в комплексе «Ротонда» с приватной террасой 41 м² и видом на море из каждого окна, в 250 метрах от воды.',
      uk: 'Квартира 2+1 у комплексі «Ротонда» з приватною терасою 41 м² та видом на море з кожного вікна, за 250 метрів від води.',
      sq: 'Apartament 2+1 në kompleksin Rotonda me tarracë private 41 m² dhe pamje nga deti nga çdo dritare, 250 metra nga uji.',
      it: 'Appartamento 2+1 nel complesso Rotonda con terrazza privata di 41 m² e vista mare da ogni finestra, a 250 metri dall’acqua.',
      pl: 'Mieszkanie 2+1 w kompleksie Rotonda z prywatnym tarasem 41 m² i widokiem na morze z każdego okna, 250 metrów od wody.',
    },
    description: {
      en: 'A two-bedroom apartment in the Rotonda complex in Plepa, Durres, 250 metres from the sea. The certificate area is 68 m², with a private terrace of 41 m² on top of it.\n\nThe sea is visible from every window, from the balcony and from the terrace. One bedroom looks out at the water directly; the second has its own balcony with the same view.\n\nThe layout is a living room with a kitchen, two separate bedrooms, a bathroom and a balcony. The flat is on the seventh floor, not the top one.\n\nThe surrounding infrastructure works year-round, which makes the flat usable as a permanent home rather than only in season.',
      ru: 'Квартира 2+1 в комплексе «Ротонда» в районе Плепа, Дуррес, в 250 метрах от моря. Площадь по сертификату — 68 м², плюс приватная терраса 41 м².\n\nМоре видно из каждого окна, с балкона и с террасы. Из одной спальни вода видна прямо из окна, у второй — собственный балкон с тем же видом.\n\nПланировка: гостиная с кухней, две отдельные спальни, санузел и балкон. Этаж седьмой, не последний.\n\nИнфраструктура вокруг работает круглый год, поэтому квартира подходит не только под сезон, но и для постоянной жизни.',
      uk: 'Квартира 2+1 у комплексі «Ротонда» в районі Плепа, Дуррес, за 250 метрів від моря. Площа за сертифікатом — 68 м², плюс приватна тераса 41 м².\n\nМоре видно з кожного вікна, з балкона й із тераси. З однієї спальні вода видніється просто з вікна, у другої — власний балкон із тим самим краєвидом.\n\nПланування: вітальня з кухнею, дві окремі спальні, санвузол і балкон. Поверх сьомий, не останній.\n\nІнфраструктура навколо працює цілий рік, тож квартира підходить не лише під сезон, а й для постійного життя.',
      sq: 'Apartament 2+1 në kompleksin Rotonda në Plepa, Durrës, 250 metra nga deti. Sipërfaqja sipas certifikatës është 68 m², plus një tarracë private prej 41 m².\n\nDeti duket nga çdo dritare, nga ballkoni dhe nga tarraca. Nga njëra dhomë gjumi uji duket drejtpërdrejt nga dritarja; e dyta ka ballkonin e vet me të njëjtën pamje.\n\nPlanimetria: ndenjë me kuzhinë, dy dhoma gjumi më vete, tualet dhe ballkon. Kati i shtatë, jo i fundit.\n\nInfrastruktura përreth funksionon gjatë gjithë vitit, prandaj apartamenti i shërben edhe banimit të përhershëm, jo vetëm sezonit.',
      it: 'Appartamento 2+1 nel complesso Rotonda a Plepa, Durazzo, a 250 metri dal mare. La superficie da certificato è di 68 m², più una terrazza privata di 41 m².\n\nIl mare si vede da ogni finestra, dal balcone e dalla terrazza. Da una camera l’acqua è visibile direttamente dalla finestra; la seconda ha un proprio balcone con la stessa vista.\n\nLa distribuzione: soggiorno con cucina, due camere separate, bagno e balcone. Settimo piano, non l’ultimo.\n\nI servizi intorno sono aperti tutto l’anno, quindi l’appartamento si presta anche alla residenza stabile e non solo alla stagione.',
      pl: 'Mieszkanie 2+1 w kompleksie Rotonda w Plepa, Durres, 250 metrów od morza. Powierzchnia według certyfikatu to 68 m², plus prywatny taras 41 m².\n\nMorze widać z każdego okna, z balkonu i z tarasu. Z jednej sypialni wodę widać wprost z okna, druga ma własny balkon z tym samym widokiem.\n\nUkład: salon z kuchnią, dwie osobne sypialnie, łazienka i balkon. Siódme piętro, nie ostatnie.\n\nInfrastruktura wokół działa przez cały rok, więc mieszkanie nadaje się nie tylko na sezon, ale i do stałego życia.',
    },
    address: {
      en: 'Rotonda complex, Plepa, Durres',
      ru: 'Комплекс «Ротонда», Плепа, Дуррес',
      uk: 'Комплекс «Ротонда», Плепа, Дуррес',
      sq: 'Kompleksi Rotonda, Plepa, Durrës',
      it: 'Complesso Rotonda, Plepa, Durazzo',
      pl: 'Kompleks Rotonda, Plepa, Durres',
    },
    offers: [
      {
        iconKey: 'balcony',
        title: {
          en: 'Private terrace, 41 m²',
          ru: 'Приватная терраса 41 м²',
          uk: 'Приватна тераса 41 м²',
          sq: 'Tarracë private 41 m²',
          it: 'Terrazza privata di 41 m²',
          pl: 'Prywatny taras 41 m²',
        },
      },
      {
        iconKey: 'waves',
        title: {
          en: 'Sea view from every window',
          ru: 'Вид на море из каждого окна',
          uk: 'Вид на море з кожного вікна',
          sq: 'Pamje nga deti nga çdo dritare',
          it: 'Vista mare da ogni finestra',
          pl: 'Widok na morze z każdego okna',
        },
      },
      {
        iconKey: 'layout',
        title: {
          en: 'Two separate bedrooms, each with a sea outlook',
          ru: 'Две отдельные спальни, обе с видом на море',
          uk: 'Дві окремі спальні, обидві з видом на море',
          sq: 'Dy dhoma gjumi më vete, të dyja me pamje nga deti',
          it: 'Due camere separate, entrambe affacciate sul mare',
          pl: 'Dwie osobne sypialnie, obie z widokiem na morze',
        },
      },
      {
        iconKey: 'map-pin',
        title: {
          en: '250 m from the sea',
          ru: '250 м до моря',
          uk: '250 м до моря',
          sq: '250 m nga deti',
          it: '250 m dal mare',
          pl: '250 m od morza',
        },
      },
    ],
  },

  {
    datoId: 'IS0c50EwT7uFGc_6YBHTAg',
    slug: 'prodazha-premialnoj-kvartiry-11-v-centre-durresa',
    city: 'durres',
    district: 'city-center-durres',
    type: 'apartment',
    status: 'sale',
    price: 94000,
    area: 52,
    bedrooms: 1,
    bathrooms: 1,
    title: {
      en: 'Renovated One-Bedroom Apartment in the Centre of Durres',
      ru: 'Квартира 1+1 с капитальным ремонтом в центре Дурреса',
      uk: 'Квартира 1+1 із капітальним ремонтом у центрі Дурреса',
      sq: 'Apartament 1+1 i rinovuar në qendër të Durrësit',
      it: 'Appartamento 1+1 ristrutturato nel centro di Durazzo',
      pl: 'Wyremontowane mieszkanie 1+1 w centrum Durres',
    },
    shortDescription: {
      en: 'A 52 m² one-bedroom flat in central Durres, fully renovated with custom-made furniture and a designer kitchen, in a 2014 building with a lift.',
      ru: 'Квартира 1+1 площадью 52 м² в центре Дурреса, с капитальным ремонтом, мебелью на заказ и дизайнерской кухней, в доме 2014 года с лифтом.',
      uk: 'Квартира 1+1 площею 52 м² у центрі Дурреса, з капітальним ремонтом, меблями на замовлення та дизайнерською кухнею, у будинку 2014 року з ліфтом.',
      sq: 'Apartament 1+1 me sipërfaqe 52 m² në qendër të Durrësit, i rinovuar tërësisht, me mobilie me porosi dhe kuzhinë dizajni, në pallat të vitit 2014 me ashensor.',
      it: 'Appartamento 1+1 di 52 m² nel centro di Durazzo,完全 ristrutturato con mobili su misura e cucina di design, in un edificio del 2014 con ascensore.',
      pl: 'Mieszkanie 1+1 o powierzchni 52 m² w centrum Durres, po kapitalnym remoncie, z meblami na wymiar i kuchnią projektową, w budynku z 2014 roku z windą.',
    },
    description: {
      en: 'A one-bedroom apartment of 52 m² in the centre of Durres, in a 2014 building with a lift and orderly management.\n\nThe flat has had a full renovation: new windows, a sound-insulated entrance door, underfloor heating in the bathroom, Italian sanitary ware and premium porcelain stoneware. The furniture is made to measure, and the kitchen is a designer fit-out with built-in appliances and a quartz worktop. Storage has been planned carefully throughout.\n\nThe entrance hall is clean, the building fully residential, and running costs are low. A parking space can be rented.\n\nThe market, supermarkets and shops are within walking distance, and the station is about 800 metres away.',
      ru: 'Квартира 1+1 площадью 52 м² в центре Дурреса, в доме 2014 года с лифтом и нормальным управлением.\n\nВ квартире сделан капитальный ремонт: новые окна, входная дверь с шумоизоляцией, тёплый пол в ванной, итальянская сантехника и керамогранит премиум-класса. Мебель выполнена на заказ, кухня — дизайнерская, со встроенной техникой и кварцевой столешницей. Места хранения продуманы по всей квартире.\n\nПодъезд чистый, дом полностью жилой, коммунальные расходы низкие. Парковочное место можно арендовать.\n\nРынок, супермаркеты и магазины — в пешей доступности, до вокзала около 800 метров.',
      uk: 'Квартира 1+1 площею 52 м² у центрі Дурреса, у будинку 2014 року з ліфтом і нормальним управлінням.\n\nУ квартирі зроблено капітальний ремонт: нові вікна, вхідні двері із шумоізоляцією, тепла підлога у ванній, італійська сантехніка та керамограніт преміумкласу. Меблі виконані на замовлення, кухня — дизайнерська, із вбудованою технікою та кварцовою стільницею. Місця зберігання продумані по всій квартирі.\n\nПідʼїзд чистий, будинок повністю житловий, комунальні витрати низькі. Паркувальне місце можна орендувати.\n\nРинок, супермаркети й магазини — у пішій доступності, до вокзалу близько 800 метрів.',
      sq: 'Apartament 1+1 me sipërfaqe 52 m² në qendër të Durrësit, në një pallat të vitit 2014 me ashensor dhe administrim të rregullt.\n\nApartamenti ka kaluar një rinovim të plotë: dritare të reja, derë hyrëse me izolim zhurme, ngrohje nën dysheme në banjë, hidrosanitare italiane dhe gres porcelanato premium. Mobiliet janë me porosi, kuzhina është e projektuar me pajisje të inkorporuara dhe pjatë pune prej kuarci. Hapësirat e ruajtjes janë menduar në çdo cep.\n\nHyrja është e pastër, pallati tërësisht i banuar dhe shpenzimet e mirëmbajtjes të ulëta. Mund të merret me qira një vend parkimi.\n\nTregu, supermarketet dhe dyqanet janë në këmbë, stacioni rreth 800 metra larg.',
      it: 'Appartamento 1+1 di 52 m² nel centro di Durazzo, in un edificio del 2014 con ascensore e gestione ordinata.\n\nL’appartamento è stato interamente ristrutturato: finestre nuove, porta d’ingresso insonorizzata, riscaldamento a pavimento in bagno, sanitari italiani e gres porcellanato di fascia alta. I mobili sono su misura e la cucina è un allestimento di design con elettrodomestici da incasso e piano in quarzo. Gli spazi di contenimento sono stati studiati ovunque.\n\nL’ingresso è pulito, l’edificio interamente residenziale e le spese contenute. È possibile affittare un posto auto.\n\nMercato, supermercati e negozi sono a piedi; la stazione dista circa 800 metri.',
      pl: 'Mieszkanie 1+1 o powierzchni 52 m² w centrum Durres, w budynku z 2014 roku z windą i uporządkowanym zarządzaniem.\n\nMieszkanie przeszło kapitalny remont: nowe okna, drzwi wejściowe z izolacją akustyczną, ogrzewanie podłogowe w łazience, włoska armatura i gres porcelanowy z wyższej półki. Meble wykonano na wymiar, kuchnia jest projektowa, ze sprzętem w zabudowie i blatem kwarcowym. Miejsca do przechowywania przemyślano w całym mieszkaniu.\n\nKlatka jest czysta, budynek w pełni mieszkalny, a koszty utrzymania niskie. Miejsce parkingowe można wynająć.\n\nTarg, supermarkety i sklepy są w zasięgu spaceru, dworzec około 800 metrów.',
    },
    address: {
      en: 'City centre, Durres',
      ru: 'Центр города, Дуррес',
      uk: 'Центр міста, Дуррес',
      sq: 'Qendra e qytetit, Durrës',
      it: 'Centro città, Durazzo',
      pl: 'Centrum miasta, Durres',
    },
    offers: [
      {
        iconKey: 'key',
        title: {
          en: 'Full renovation, move-in ready',
          ru: 'Капитальный ремонт, заезжай и живи',
          uk: 'Капітальний ремонт, заїжджай і живи',
          sq: 'Rinovim i plotë, gati për t’u banuar',
          it: 'Ristrutturazione completa, pronto da abitare',
          pl: 'Kapitalny remont, gotowe do zamieszkania',
        },
      },
      {
        iconKey: 'sofa',
        title: {
          en: 'Made-to-measure furniture and designer kitchen',
          ru: 'Мебель на заказ и дизайнерская кухня',
          uk: 'Меблі на замовлення та дизайнерська кухня',
          sq: 'Mobilie me porosi dhe kuzhinë dizajni',
          it: 'Mobili su misura e cucina di design',
          pl: 'Meble na wymiar i kuchnia projektowa',
        },
      },
      {
        iconKey: 'elevator',
        title: {
          en: '2014 building with a lift, low running costs',
          ru: 'Дом 2014 года с лифтом, низкие расходы',
          uk: 'Будинок 2014 року з ліфтом, низькі витрати',
          sq: 'Pallat i vitit 2014 me ashensor, shpenzime të ulëta',
          it: 'Edificio del 2014 con ascensore, spese contenute',
          pl: 'Budynek z 2014 roku z windą, niskie koszty',
        },
      },
      {
        iconKey: 'map-pin',
        title: {
          en: 'City centre, station about 800 m away',
          ru: 'Центр города, до вокзала около 800 м',
          uk: 'Центр міста, до вокзалу близько 800 м',
          sq: 'Qendër qyteti, stacioni rreth 800 m',
          it: 'Centro città, stazione a circa 800 m',
          pl: 'Centrum miasta, dworzec około 800 m',
        },
      },
      {
        iconKey: 'parking',
        title: {
          en: 'Parking space available to rent',
          ru: 'Есть возможность арендовать парковку',
          uk: 'Є можливість орендувати паркомісце',
          sq: 'Mundësi qiraje për vend parkimi',
          it: 'Posto auto disponibile in affitto',
          pl: 'Możliwość wynajęcia miejsca parkingowego',
        },
      },
    ],
  },

  {
    datoId: 'EFhNDgxyTG6LbELQm6V74w',
    slug: 'prodazha-prostornoj-kvartiry-212-100m-ot-morya',
    city: 'durres',
    district: 'plazh',
    type: 'apartment',
    status: 'sale',
    price: 145000,
    area: 96,
    bedrooms: 2,
    bathrooms: 2,
    title: {
      en: 'Spacious Two-Bedroom Apartment 100 m from the Sea — Plazh, Durres',
      ru: 'Просторная квартира 2+1 в 100 м от моря — Пляж, Дуррес',
      uk: 'Простора квартира 2+1 за 100 м від моря — Пляж, Дуррес',
      sq: 'Apartament i gjerë 2+1, 100 m nga deti — Plazh, Durrës',
      it: 'Ampio appartamento 2+1 a 100 m dal mare — Plazh, Durazzo',
      pl: 'Przestronne mieszkanie 2+1, 100 m od morza — Plazh, Durres',
    },
    shortDescription: {
      en: '96 m² apartment with two bedrooms, two bathrooms and two balconies, a hundred metres from the beach in Plazh, sold furnished and equipped.',
      ru: 'Квартира 96 м² с двумя спальнями, двумя санузлами и двумя балконами, в ста метрах от пляжа в районе Пляж, с мебелью и техникой.',
      uk: 'Квартира 96 м² із двома спальнями, двома санвузлами та двома балконами, за сто метрів від пляжу в районі Пляж, із меблями й технікою.',
      sq: 'Apartament 96 m² me dy dhoma gjumi, dy tualete dhe dy ballkone, njëqind metra nga plazhi në Plazh, i mobiluar dhe i pajisur.',
      it: 'Appartamento di 96 m² con due camere, due bagni e due balconi, a cento metri dalla spiaggia a Plazh, arredato e attrezzato.',
      pl: 'Mieszkanie 96 m² z dwiema sypialniami, dwiema łazienkami i dwoma balkonami, sto metrów od plaży w Plazh, umeblowane i wyposażone.',
    },
    description: {
      en: 'A 96 m² apartment in Plazh, one of the most sought-after districts of Durres, a hundred metres from the sea. Sixth floor of seven, in a building about fifteen years old.\n\nThe layout gives a large living room, two separate bedrooms, two bathrooms and two balconies. Each balcony has a partial sea view.\n\nThe flat comes fully furnished and equipped, so it can be let from the day of purchase.\n\nThe district keeps its shops, cafés, restaurants, pharmacies and transport running through the year, and the beach is a hundred metres away.',
      ru: 'Квартира 96 м² в районе Пляж — одном из самых востребованных в Дурресе, в ста метрах от моря. Шестой этаж из семи, дому около пятнадцати лет.\n\nПланировка: просторная гостиная, две отдельные спальни, два санузла и два балкона. С каждого балкона открывается частичный вид на море.\n\nКвартира полностью меблирована и оборудована техникой, так что сдавать её можно с момента покупки.\n\nВ районе круглый год работают магазины, кафе, рестораны, аптеки и транспорт, до пляжа сто метров.',
      uk: 'Квартира 96 м² у районі Пляж — одному з найзатребуваніших у Дурресі, за сто метрів від моря. Шостий поверх із семи, будинку близько пʼятнадцяти років.\n\nПланування: простора вітальня, дві окремі спальні, два санвузли й два балкони. З кожного балкона відкривається частковий вид на море.\n\nКвартира повністю вмебльована й обладнана технікою, тож здавати її можна з моменту купівлі.\n\nУ районі цілий рік працюють магазини, кафе, ресторани, аптеки й транспорт, до пляжу сто метрів.',
      sq: 'Apartament 96 m² në Plazh, një nga zonat më të kërkuara të Durrësit, njëqind metra nga deti. Kati i gjashtë nga shtatë, në një pallat rreth pesëmbëdhjetë vjeçar.\n\nPlanimetria ofron një ndenjë të gjerë, dy dhoma gjumi më vete, dy tualete dhe dy ballkone. Nga secili ballkon ka pamje të pjesshme nga deti.\n\nApartamenti vjen plotësisht i mobiluar dhe i pajisur, prandaj mund të jepet me qira që nga dita e blerjes.\n\nZona i mban dyqanet, kafenetë, restorantet, farmacitë dhe transportin të hapura gjatë gjithë vitit, ndërsa plazhi është njëqind metra larg.',
      it: 'Appartamento di 96 m² a Plazh, uno dei quartieri più richiesti di Durazzo, a cento metri dal mare. Sesto piano su sette, in un edificio di circa quindici anni.\n\nLa distribuzione offre un ampio soggiorno, due camere separate, due bagni e due balconi. Da ciascun balcone si gode una vista parziale sul mare.\n\nL’appartamento è completamente arredato e attrezzato, quindi può essere affittato dal giorno dell’acquisto.\n\nIl quartiere mantiene negozi, bar, ristoranti, farmacie e trasporti attivi tutto l’anno, e la spiaggia dista cento metri.',
      pl: 'Mieszkanie o powierzchni 96 m² w Plazh, jednej z najbardziej poszukiwanych dzielnic Durres, sto metrów od morza. Szóste piętro z siedmiu, budynek ma około piętnastu lat.\n\nUkład daje przestronny salon, dwie osobne sypialnie, dwie łazienki i dwa balkony. Z każdego balkonu roztacza się częściowy widok na morze.\n\nMieszkanie jest w pełni umeblowane i wyposażone, więc można je wynajmować od dnia zakupu.\n\nDzielnica utrzymuje sklepy, kawiarnie, restauracje, apteki i transport czynne przez cały rok, a plaża jest sto metrów dalej.',
    },
    address: {
      en: 'Plazh (Durres Beach), Durres',
      ru: 'Район Пляж, Дуррес',
      uk: 'Район Пляж, Дуррес',
      sq: 'Plazh, Durrës',
      it: 'Plazh, Durazzo',
      pl: 'Plazh, Durres',
    },
    offers: [
      {
        iconKey: 'layout',
        title: {
          en: 'Two bedrooms, two bathrooms, two balconies',
          ru: 'Две спальни, два санузла, два балкона',
          uk: 'Дві спальні, два санвузли, два балкони',
          sq: 'Dy dhoma gjumi, dy tualete, dy ballkone',
          it: 'Due camere, due bagni, due balconi',
          pl: 'Dwie sypialnie, dwie łazienki, dwa balkony',
        },
      },
      {
        iconKey: 'waves',
        title: {
          en: '100 m from the beach, partial sea view',
          ru: '100 м до пляжа, частичный вид на море',
          uk: '100 м до пляжу, частковий вид на море',
          sq: '100 m nga plazhi, pamje e pjesshme nga deti',
          it: '100 m dalla spiaggia, vista mare parziale',
          pl: '100 m od plaży, częściowy widok na morze',
        },
      },
      {
        iconKey: 'sofa',
        title: {
          en: 'Furnished and equipped, lettable immediately',
          ru: 'С мебелью и техникой, сдавать можно сразу',
          uk: 'З меблями й технікою, здавати можна одразу',
          sq: 'E mobiluar dhe e pajisur, gati për qira',
          it: 'Arredato e attrezzato, affittabile subito',
          pl: 'Umeblowane i wyposażone, od razu pod wynajem',
        },
      },
      {
        iconKey: 'building',
        title: {
          en: 'Year-round infrastructure in the district',
          ru: 'Круглогодичная инфраструктура в районе',
          uk: 'Цілорічна інфраструктура в районі',
          sq: 'Infrastrukturë gjatë gjithë vitit në zonë',
          it: 'Servizi attivi tutto l’anno nel quartiere',
          pl: 'Całoroczna infrastruktura w dzielnicy',
        },
      },
    ],
  },

  {
    datoId: 'aDZUN1RpTyCAZYkbX1XtJg',
    slug: 'prodazha-kvartiry-11-u-morya-or-67m2',
    city: 'durres',
    district: 'plazh',
    type: 'apartment',
    status: 'sale',
    price: 90000,
    area: 67,
    bedrooms: 1,
    bathrooms: 1,
    title: {
      en: 'One-Bedroom Apartment 67 m² near the Sea — Plazh, Durres',
      ru: 'Квартира 1+1, 67 м², у моря — Пляж, Дуррес',
      uk: 'Квартира 1+1, 67 м², біля моря — Пляж, Дуррес',
      sq: 'Apartament 1+1, 67 m², pranë detit — Plazh, Durrës',
      it: 'Appartamento 1+1 di 67 m² vicino al mare — Plazh, Durazzo',
      pl: 'Mieszkanie 1+1, 67 m², blisko morza — Plazh, Durres',
    },
    shortDescription: {
      en: 'A 67 m² one-bedroom flat on the fifth floor in Plazh, three hundred metres from the sea, furnished and equipped.',
      ru: 'Квартира 1+1 площадью 67 м² на пятом этаже в районе Пляж, в трёхстах метрах от моря, с мебелью и техникой.',
      uk: 'Квартира 1+1 площею 67 м² на пʼятому поверсі в районі Пляж, за триста метрів від моря, з меблями й технікою.',
      sq: 'Apartament 1+1 me sipërfaqe 67 m² në katin e pestë në Plazh, treqind metra nga deti, i mobiluar dhe i pajisur.',
      it: 'Appartamento 1+1 di 67 m² al quinto piano a Plazh, a trecento metri dal mare, arredato e attrezzato.',
      pl: 'Mieszkanie 1+1 o powierzchni 67 m² na piątym piętrze w Plazh, trzysta metrów od morza, umeblowane i wyposażone.',
    },
    description: {
      en: 'A one-bedroom apartment of 67 m² by certificate in Plazh, Durres, three hundred metres from the sea. Fifth floor.\n\nAll the furniture and appliances needed are already in place, so the flat can be lived in or let straight away.\n\nPlazh is one of the districts where shops, cafés and transport stay open through the winter as well as the season, which is what keeps the flats here liquid.',
      ru: 'Квартира 1+1 площадью 67 м² по сертификату в районе Пляж, Дуррес, в трёхстах метрах от моря. Пятый этаж.\n\nВся необходимая мебель и техника уже на месте, так что заехать или начать сдавать можно сразу.\n\nПляж — один из районов, где магазины, кафе и транспорт работают и зимой, и в сезон. Именно это делает здешние квартиры ликвидными.',
      uk: 'Квартира 1+1 площею 67 м² за сертифікатом у районі Пляж, Дуррес, за триста метрів від моря. Пʼятий поверх.\n\nУсі потрібні меблі й техніка вже на місці, тож заїхати або почати здавати можна одразу.\n\nПляж — один із районів, де магазини, кафе й транспорт працюють і взимку, і в сезон. Саме це робить тутешні квартири ліквідними.',
      sq: 'Apartament 1+1 me 67 m² sipas certifikatës në Plazh, Durrës, treqind metra nga deti. Kati i pestë.\n\nTë gjitha mobiliet dhe pajisjet e nevojshme janë tashmë aty, prandaj mund të banohet ose të jepet me qira menjëherë.\n\nPlazhi është një nga zonat ku dyqanet, kafenetë dhe transporti punojnë edhe në dimër, jo vetëm në sezon. Pikërisht kjo i mban apartamentet këtu të likuide.',
      it: 'Appartamento 1+1 di 67 m² da certificato a Plazh, Durazzo, a trecento metri dal mare. Quinto piano.\n\nTutti i mobili e gli elettrodomestici necessari sono già presenti, quindi si può abitare o affittare da subito.\n\nPlazh è uno dei quartieri in cui negozi, bar e trasporti restano aperti anche d’inverno, oltre che in stagione: è questo a mantenere liquidi gli appartamenti della zona.',
      pl: 'Mieszkanie 1+1 o powierzchni 67 m² według certyfikatu w Plazh, Durres, trzysta metrów od morza. Piąte piętro.\n\nWszystkie potrzebne meble i sprzęt są już na miejscu, więc można się wprowadzić lub zacząć wynajmować od razu.\n\nPlazh to jedna z dzielnic, w której sklepy, kawiarnie i transport działają także zimą, nie tylko w sezonie. To właśnie utrzymuje płynność tutejszych mieszkań.',
    },
    address: {
      en: 'Plazh (Durres Beach), Durres',
      ru: 'Район Пляж, Дуррес',
      uk: 'Район Пляж, Дуррес',
      sq: 'Plazh, Durrës',
      it: 'Plazh, Durazzo',
      pl: 'Plazh, Durres',
    },
    offers: [
      {
        iconKey: 'waves',
        title: {
          en: '300 m from the sea',
          ru: '300 м до моря',
          uk: '300 м до моря',
          sq: '300 m nga deti',
          it: '300 m dal mare',
          pl: '300 m od morza',
        },
      },
      {
        iconKey: 'sofa',
        title: {
          en: 'Furnished and equipped',
          ru: 'С мебелью и техникой',
          uk: 'З меблями й технікою',
          sq: 'E mobiluar dhe e pajisur',
          it: 'Arredato e attrezzato',
          pl: 'Umeblowane i wyposażone',
        },
      },
      {
        iconKey: 'building',
        title: {
          en: 'District open year-round',
          ru: 'Район работает круглый год',
          uk: 'Район працює цілий рік',
          sq: 'Zonë aktive gjatë gjithë vitit',
          it: 'Quartiere attivo tutto l’anno',
          pl: 'Dzielnica czynna przez cały rok',
        },
      },
    ],
    review:
      'Source claims the flat qualifies three people for a residence permit. Dropped from the copy — legal claim about the buyer, not the property.',
  },

  {
    datoId: 'HYLanVFPRFSwmvOSd5Bzyg',
    slug: 'prodazha-mali-i-robit-new-residence-11-or-42m2',
    city: 'durres',
    district: 'mali-i-robit',
    type: 'apartment',
    status: 'sale',
    price: 87000,
    area: 42,
    bedrooms: 1,
    bathrooms: 1,
    title: {
      en: 'New-Build One-Bedroom Apartment 42 m² — Mali i Robit, Durres',
      ru: 'Квартира 1+1, 42 м², в новостройке — Мали и Робит, Дуррес',
      uk: 'Квартира 1+1, 42 м², у новобудові — Малі і Робіт, Дуррес',
      sq: 'Apartament 1+1, 42 m², në ndërtim të ri — Mali i Robit, Durrës',
      it: 'Appartamento 1+1 di 42 m² in nuova costruzione — Mali i Robit, Durazzo',
      pl: 'Mieszkanie 1+1, 42 m², w nowym budynku — Mali i Robit, Durres',
    },
    shortDescription: {
      en: 'A 42 m² apartment in a 2026 building in Mali i Robit, 250 metres from the sea, furnished with Multi Split heating and cooling in every room.',
      ru: 'Квартира 42 м² в доме 2026 года в Мали и Робит, в 250 метрах от моря, с мебелью и системой Multi Split — отопление и охлаждение в каждой комнате.',
      uk: 'Квартира 42 м² у будинку 2026 року в Малі і Робіт, за 250 метрів від моря, з меблями та системою Multi Split — опалення й охолодження в кожній кімнаті.',
      sq: 'Apartament 42 m² në një pallat të vitit 2026 në Mali i Robit, 250 metra nga deti, i mobiluar me sistem Multi Split për ngrohje e ftohje në çdo dhomë.',
      it: 'Appartamento di 42 m² in un edificio del 2026 a Mali i Robit, a 250 metri dal mare, arredato con sistema Multi Split per riscaldamento e raffrescamento in ogni stanza.',
      pl: 'Mieszkanie 42 m² w budynku z 2026 roku w Mali i Robit, 250 metrów od morza, umeblowane, z systemem Multi Split — ogrzewanie i chłodzenie w każdym pomieszczeniu.',
    },
    description: {
      en: 'A one-bedroom apartment of 42 m² in a new 2026 building in Mali i Robit, 250 metres from the sea. Third floor, with a lift rated for eight people.\n\nThe layout is a spacious living room with a kitchen, a separate bedroom and a modern bathroom.\n\nIt is sold furnished, with contemporary furniture and appliances, a Multi Split system providing heating and cooling in each room, modern lighting, good-quality finishes and services suited to living here through the winter. A parking space can be bought separately.\n\nMali i Robit is a green, well-regarded stretch of the coast, used for living, holidays and letting alike.',
      ru: 'Квартира 1+1 площадью 42 м² в новом доме 2026 года в районе Мали и Робит, в 250 метрах от моря. Третий этаж, лифт на восемь человек.\n\nПланировка: просторная гостиная с кухней, отдельная спальня и современный санузел.\n\nПродаётся с мебелью — современная обстановка и техника, система Multi Split с отоплением и охлаждением в каждой комнате, современное освещение, качественная отделка и коммуникации, рассчитанные в том числе на зиму. Парковочное место можно приобрести отдельно.\n\nМали и Робит — зелёный и уважаемый участок побережья, который одинаково используют для жизни, отдыха и аренды.',
      uk: 'Квартира 1+1 площею 42 м² у новому будинку 2026 року в районі Малі і Робіт, за 250 метрів від моря. Третій поверх, ліфт на вісім осіб.\n\nПланування: простора вітальня з кухнею, окрема спальня та сучасний санвузол.\n\nПродається з меблями — сучасна обстановка й техніка, система Multi Split з опаленням і охолодженням у кожній кімнаті, сучасне освітлення, якісне оздоблення та комунікації, розраховані зокрема й на зиму. Паркувальне місце можна придбати окремо.\n\nМалі і Робіт — зелена й шанована ділянка узбережжя, яку однаково використовують для життя, відпочинку та оренди.',
      sq: 'Apartament 1+1 me sipërfaqe 42 m² në një pallat të ri të vitit 2026 në Mali i Robit, 250 metra nga deti. Kati i tretë, me ashensor për tetë veta.\n\nPlanimetria: ndenjë e gjerë me kuzhinë, dhomë gjumi më vete dhe tualet modern.\n\nShitet i mobiluar — mobilie e pajisje moderne, sistem Multi Split me ngrohje dhe ftohje në çdo dhomë, ndriçim modern, materiale cilësore dhe instalime të përshtatshme edhe për dimrin. Vendi i parkimit mund të blihet veçmas.\n\nMali i Robit është një pjesë e gjelbër dhe e vlerësuar e bregdetit, e përdorur njësoj për banim, pushime dhe qira.',
      it: 'Appartamento 1+1 di 42 m² in un nuovo edificio del 2026 a Mali i Robit, a 250 metri dal mare. Terzo piano, con ascensore per otto persone.\n\nLa distribuzione: ampio soggiorno con cucina, camera da letto separata e bagno moderno.\n\nViene venduto arredato, con mobili ed elettrodomestici contemporanei, un sistema Multi Split che riscalda e raffresca ogni stanza, illuminazione moderna, finiture di buona qualità e impianti adatti anche all’inverno. Il posto auto è acquistabile separatamente.\n\nMali i Robit è un tratto di costa verde e ben considerato, usato allo stesso modo per abitare, per le vacanze e per l’affitto.',
      pl: 'Mieszkanie 1+1 o powierzchni 42 m² w nowym budynku z 2026 roku w Mali i Robit, 250 metrów od morza. Trzecie piętro, winda na osiem osób.\n\nUkład: przestronny salon z kuchnią, osobna sypialnia i nowoczesna łazienka.\n\nSprzedawane z meblami — współczesne wyposażenie i sprzęt, system Multi Split z ogrzewaniem i chłodzeniem w każdym pomieszczeniu, nowoczesne oświetlenie, dobre wykończenie i instalacje przystosowane także do zimy. Miejsce parkingowe można kupić osobno.\n\nMali i Robit to zielony i ceniony odcinek wybrzeża, wykorzystywany zarówno do życia, jak i na wakacje oraz pod wynajem.',
    },
    address: {
      en: 'Mali i Robit, Durres',
      ru: 'Мали и Робит, Дуррес',
      uk: 'Малі і Робіт, Дуррес',
      sq: 'Mali i Robit, Durrës',
      it: 'Mali i Robit, Durazzo',
      pl: 'Mali i Robit, Durres',
    },
    offers: [
      {
        iconKey: 'building',
        title: {
          en: 'New 2026 building',
          ru: 'Новый дом 2026 года',
          uk: 'Новий будинок 2026 року',
          sq: 'Pallat i ri i vitit 2026',
          it: 'Edificio nuovo del 2026',
          pl: 'Nowy budynek z 2026 roku',
        },
      },
      {
        iconKey: 'snowflake',
        title: {
          en: 'Multi Split heating and cooling in every room',
          ru: 'Multi Split: отопление и охлаждение в каждой комнате',
          uk: 'Multi Split: опалення й охолодження в кожній кімнаті',
          sq: 'Multi Split: ngrohje dhe ftohje në çdo dhomë',
          it: 'Multi Split: riscaldamento e raffrescamento in ogni stanza',
          pl: 'Multi Split: ogrzewanie i chłodzenie w każdym pomieszczeniu',
        },
      },
      {
        iconKey: 'waves',
        title: {
          en: '250 m from the sea',
          ru: '250 м до моря',
          uk: '250 м до моря',
          sq: '250 m nga deti',
          it: '250 m dal mare',
          pl: '250 m od morza',
        },
      },
      {
        iconKey: 'sofa',
        title: {
          en: 'Fully furnished with modern appliances',
          ru: 'Полностью меблирована, современная техника',
          uk: 'Повністю вмебльована, сучасна техніка',
          sq: 'Plotësisht e mobiluar, pajisje moderne',
          it: 'Completamente arredato, elettrodomestici moderni',
          pl: 'W pełni umeblowane, nowoczesny sprzęt',
        },
      },
      {
        iconKey: 'parking',
        title: {
          en: 'Parking space available to buy',
          ru: 'Парковочное место можно купить',
          uk: 'Паркомісце можна купити',
          sq: 'Vend parkimi i blershëm',
          it: 'Posto auto acquistabile',
          pl: 'Miejsce parkingowe do kupienia',
        },
      },
    ],
  },
]
