import type {PropertyContent} from './types'

/** Objects 1–5: Vlorë house, Golem terrace flat, Plazh 1+1, Plazh studio, Shkëmbi i Kavajës. */
export const BATCH_1: PropertyContent[] = [
  {
    datoId: 'CHdi9GS3Qn6JsuDl43FXsw',
    slug: 'prodazha-doma-vo-vlere',
    city: 'vlore',
    type: 'house',
    status: 'sale',
    price: 135000,
    area: 109,
    bedrooms: 2,
    bathrooms: 1,
    title: {
      en: 'House for Sale in Vlore — 109 m², 3 km from the Sea',
      ru: 'Дом во Влёре — 109 м², 3 км до моря',
      uk: 'Будинок у Влері — 109 м², 3 км до моря',
      sq: 'Shtëpi në shitje në Vlorë — 109 m², 3 km nga deti',
      it: 'Casa in vendita a Valona — 109 m², 3 km dal mare',
      pl: 'Dom na sprzedaż we Wlorze — 109 m², 3 km od morza',
    },
    shortDescription: {
      en: 'A two-bedroom house in a quiet part of Vlore, three kilometres from the sea. House and land hold separate certificates, and it is sold fully furnished.',
      ru: 'Двухспальный дом в тихом районе Влёры, в трёх километрах от моря. На дом и на землю оформлены отдельные сертификаты, продаётся с мебелью.',
      uk: 'Будинок із двома спальнями в тихому районі Влери, за три кілометри від моря. На будинок і на землю окремі сертифікати, продається з меблями.',
      sq: 'Shtëpi me dy dhoma gjumi në një zonë të qetë të Vlorës, tre kilometra nga deti. Shtëpia dhe trualli kanë certifikata të veçanta, shitet e mobiluar.',
      it: 'Casa con due camere in una zona tranquilla di Valona, a tre chilometri dal mare. Casa e terreno hanno certificati separati, venduta arredata.',
      pl: 'Dom z dwiema sypialniami w spokojnej części Wlory, trzy kilometry od morza. Dom i działka mają osobne certyfikaty, sprzedawany z meblami.',
    },
    description: {
      en: 'A two-bedroom house in one of the quieter residential parts of Vlore, three kilometres from the sea. The certificate area is 109 m².\n\nThe paperwork is unusually clean for this market: the house and the land plot each hold their own certificate, both in order.\n\nThe house is sold fully furnished and equipped. Part of the furniture and appliances were bought new and have not been used, so it needs no work before moving in. The owner will consider a reasonable offer after a viewing.',
      ru: 'Дом с двумя спальнями в одном из тихих жилых районов Влёры, в трёх километрах от моря. Площадь по сертификату — 109 м².\n\nДокументы в порядке, причём в редком для этого рынка объёме: на дом и на земельный участок оформлены отдельные сертификаты.\n\nДом продаётся полностью меблированным и с техникой. Часть мебели и техники докуплена новой и не использовалась, поэтому вкладываться перед заселением не придётся. Собственник готов обсудить разумный торг после осмотра.',
      uk: 'Будинок із двома спальнями в одному з тихих житлових районів Влери, за три кілометри від моря. Площа за сертифікатом — 109 м².\n\nДокументи в порядку, причому в рідкісному для цього ринку обсязі: на будинок і на земельну ділянку оформлені окремі сертифікати.\n\nБудинок продається повністю вмебльованим і з технікою. Частину меблів і техніки докуплено новою та не використано, тож вкладатися перед заселенням не доведеться. Власник готовий обговорити розумний торг після огляду.',
      sq: 'Shtëpi me dy dhoma gjumi në një nga zonat e qeta të banimit në Vlorë, tre kilometra nga deti. Sipërfaqja sipas certifikatës është 109 m².\n\nDokumentacioni është i plotë dhe i rrallë për këtë treg: shtëpia dhe trualli kanë secila certifikatën e vet.\n\nShtëpia shitet plotësisht e mobiluar dhe e pajisur. Një pjesë e mobilieve dhe e pajisjeve është blerë e re dhe nuk është përdorur, prandaj nuk kërkon investim para se të banoni. Pronari pranon të diskutojë një ofertë të arsyeshme pas vizitës.',
      it: 'Casa con due camere da letto in una delle zone residenziali tranquille di Valona, a tre chilometri dal mare. La superficie da certificato è di 109 m².\n\nLa documentazione è completa e insolitamente ordinata per questo mercato: la casa e il terreno hanno ciascuno il proprio certificato.\n\nLa casa è venduta completamente arredata e attrezzata. Parte dei mobili e degli elettrodomestici è stata acquistata nuova e non è mai stata usata, quindi non serve alcun intervento prima di trasferirsi. Il proprietario valuta un’offerta ragionevole dopo la visita.',
      pl: 'Dom z dwiema sypialniami w jednej ze spokojnych dzielnic mieszkaniowych Wlory, trzy kilometry od morza. Powierzchnia według certyfikatu to 109 m².\n\nDokumentacja jest kompletna i jak na ten rynek wyjątkowo uporządkowana: dom i działka mają osobne certyfikaty.\n\nDom sprzedawany jest w pełni umeblowany i wyposażony. Część mebli i sprzętu kupiono nowe i nie były używane, więc przed wprowadzeniem się nie trzeba nic robić. Właściciel rozważy rozsądną ofertę po obejrzeniu.',
    },
    address: {
      en: 'Vlore, quiet residential area 3 km from the sea',
      ru: 'Влёра, тихий жилой район в 3 км от моря',
      uk: 'Влера, тихий житловий район за 3 км від моря',
      sq: 'Vlorë, zonë e qetë banimi 3 km nga deti',
      it: 'Valona, zona residenziale tranquilla a 3 km dal mare',
      pl: 'Wlora, spokojna dzielnica mieszkaniowa 3 km od morza',
    },
    offers: [
      {
        iconKey: 'shield',
        title: {
          en: 'Separate certificates for house and land',
          ru: 'Отдельные сертификаты на дом и на землю',
          uk: 'Окремі сертифікати на будинок і на землю',
          sq: 'Certifikata të veçanta për shtëpinë dhe truallin',
          it: 'Certificati separati per casa e terreno',
          pl: 'Osobne certyfikaty na dom i działkę',
        },
      },
      {
        iconKey: 'sofa',
        title: {
          en: 'Fully furnished and equipped',
          ru: 'Полностью меблирован, с техникой',
          uk: 'Повністю вмебльований, із технікою',
          sq: 'Plotësisht i mobiluar dhe i pajisur',
          it: 'Completamente arredata e attrezzata',
          pl: 'W pełni umeblowany i wyposażony',
        },
      },
      {
        iconKey: 'key',
        title: {
          en: 'Move-in ready, no renovation needed',
          ru: 'Готов к заселению, без вложений',
          uk: 'Готовий до заселення, без вкладень',
          sq: 'Gati për t’u banuar, pa investime',
          it: 'Pronta da abitare, senza lavori',
          pl: 'Gotowy do zamieszkania, bez remontu',
        },
      },
      {
        iconKey: 'tree',
        title: {
          en: 'Quiet residential area',
          ru: 'Тихий жилой район',
          uk: 'Тихий житловий район',
          sq: 'Zonë e qetë banimi',
          it: 'Zona residenziale tranquilla',
          pl: 'Spokojna dzielnica mieszkaniowa',
        },
      },
      {
        iconKey: 'waves',
        title: {
          en: '3 km from the sea',
          ru: '3 км до моря',
          uk: '3 км до моря',
          sq: '3 km nga deti',
          it: '3 km dal mare',
          pl: '3 km od morza',
        },
      },
    ],
  },

  {
    datoId: 'eUS-99NvRC2vPes1NnUnCA',
    slug: 'prodazha-kvartiry-11-s-sobstvennoj-terassoj',
    city: 'durres',
    district: 'golem-durres',
    type: 'apartment',
    status: 'sale',
    price: 65000,
    area: 56,
    bedrooms: 1,
    bathrooms: 1,
    title: {
      en: 'One-Bedroom Apartment with Private Terrace in Golem, Durres',
      ru: 'Квартира 1+1 с собственной террасой в Големе, Дуррес',
      uk: 'Квартира 1+1 із власною терасою в Големі, Дуррес',
      sq: 'Apartament 1+1 me tarracë private në Golem, Durrës',
      it: 'Appartamento 1+1 con terrazza privata a Golem, Durazzo',
      pl: 'Mieszkanie 1+1 z prywatnym tarasem w Golem, Durres',
    },
    shortDescription: {
      en: 'Ground-floor one-bedroom apartment in Golem with a private 12.5 m² terrace, sold furnished and equipped.',
      ru: 'Квартира 1+1 на первом этаже в Големе с приватной террасой 12,5 м², продаётся с мебелью и техникой.',
      uk: 'Квартира 1+1 на першому поверсі в Големі з приватною терасою 12,5 м², продається з меблями й технікою.',
      sq: 'Apartament 1+1 në katin përdhes në Golem me tarracë private 12,5 m², shitet i mobiluar dhe i pajisur.',
      it: 'Appartamento 1+1 al piano terra a Golem con terrazza privata di 12,5 m², venduto arredato e attrezzato.',
      pl: 'Mieszkanie 1+1 na parterze w Golem z prywatnym tarasem 12,5 m², sprzedawane z meblami i sprzętem.',
    },
    description: {
      en: 'A one-bedroom apartment on the ground floor in Golem, Durres, with its own green terrace of 12.5 m².\n\nThe certificate area is 44 m²; with the terrace the listing measures 56 m².\n\nIt is ready to live in as it stands: all furniture, appliances, air conditioning and a new bathroom are in place, so nothing needs to be spent before moving in. It suits year-round living, a holiday base, or letting.',
      ru: 'Квартира 1+1 на первом этаже в Големе, Дуррес, с собственной зелёной террасой 12,5 м².\n\nПлощадь по сертификату — 44 м²; вместе с террасой объект занимает 56 м².\n\nЖильё готово к проживанию как есть: вся мебель, техника, кондиционер и новый санузел уже на месте, вкладываться перед заселением не нужно. Подходит для круглогодичной жизни, отдыха или сдачи в аренду.',
      uk: 'Квартира 1+1 на першому поверсі в Големі, Дуррес, із власною зеленою терасою 12,5 м².\n\nПлоща за сертифікатом — 44 м²; разом із терасою обʼєкт займає 56 м².\n\nЖитло готове до проживання як є: усі меблі, техніка, кондиціонер і новий санвузол уже на місці, вкладатися перед заселенням не потрібно. Підходить для цілорічного життя, відпочинку або оренди.',
      sq: 'Apartament 1+1 në katin përdhes në Golem, Durrës, me tarracë private të gjelbër prej 12,5 m².\n\nSipërfaqja sipas certifikatës është 44 m²; bashkë me tarracën prona arrin 56 m².\n\nËshtë gati për t’u banuar ashtu siç është: mobiliet, pajisjet, kondicioneri dhe tualeti i ri janë të gjitha në vend, pa nevojë për shpenzime para se të hyni. I përshtatet banimit gjatë gjithë vitit, pushimeve ose qirasë.',
      it: 'Appartamento 1+1 al piano terra a Golem, Durazzo, con terrazza privata verde di 12,5 m².\n\nLa superficie da certificato è di 44 m²; con la terrazza l’immobile misura 56 m².\n\nÈ pronto da abitare così com’è: mobili, elettrodomestici, aria condizionata e bagno nuovo sono già presenti, senza spese prima di entrare. Adatto alla vita tutto l’anno, alle vacanze o all’affitto.',
      pl: 'Mieszkanie 1+1 na parterze w Golem, Durres, z własnym zielonym tarasem o powierzchni 12,5 m².\n\nPowierzchnia według certyfikatu to 44 m²; razem z tarasem nieruchomość ma 56 m².\n\nJest gotowe do zamieszkania w obecnym stanie: meble, sprzęt, klimatyzacja i nowa łazienka są już na miejscu, więc przed wprowadzeniem nie trzeba nic dokładać. Nadaje się do życia przez cały rok, na wakacje lub pod wynajem.',
    },
    address: {
      en: 'Golem, Durres',
      ru: 'Голем, Дуррес',
      uk: 'Голем, Дуррес',
      sq: 'Golem, Durrës',
      it: 'Golem, Durazzo',
      pl: 'Golem, Durres',
    },
    offers: [
      {
        iconKey: 'balcony',
        title: {
          en: 'Private terrace, 12.5 m²',
          ru: 'Приватная терраса 12,5 м²',
          uk: 'Приватна тераса 12,5 м²',
          sq: 'Tarracë private 12,5 m²',
          it: 'Terrazza privata di 12,5 m²',
          pl: 'Prywatny taras 12,5 m²',
        },
      },
      {
        iconKey: 'sofa',
        title: {
          en: 'Furnished, with appliances and air conditioning',
          ru: 'С мебелью, техникой и кондиционером',
          uk: 'З меблями, технікою та кондиціонером',
          sq: 'E mobiluar, me pajisje dhe kondicioner',
          it: 'Arredato, con elettrodomestici e aria condizionata',
          pl: 'Umeblowane, ze sprzętem i klimatyzacją',
        },
      },
      {
        iconKey: 'key',
        title: {
          en: 'New bathroom, nothing to spend before moving in',
          ru: 'Новый санузел, вложений не требует',
          uk: 'Новий санвузол, вкладень не потребує',
          sq: 'Tualet i ri, pa shpenzime shtesë',
          it: 'Bagno nuovo, nessuna spesa prima di entrare',
          pl: 'Nowa łazienka, bez dodatkowych nakładów',
        },
      },
      {
        iconKey: 'home',
        title: {
          en: 'Ground floor, no stairs',
          ru: 'Первый этаж, без лестниц',
          uk: 'Перший поверх, без сходів',
          sq: 'Kati përdhes, pa shkallë',
          it: 'Piano terra, senza scale',
          pl: 'Parter, bez schodów',
        },
      },
    ],
    review:
      'Source claims the certificate area qualifies two people for a residence permit. Dropped from the copy — that is a legal claim tied to the buyer, not to the property.',
  },

  {
    datoId: 'bKOFugRqSgmIF3v4OctYjA',
    slug: 'prodazha-uyutnoy-kvartiry-1-1-50m-ot-morya',
    city: 'durres',
    district: 'plazh',
    type: 'apartment',
    status: 'sale',
    price: 85000,
    area: 44,
    bedrooms: 1,
    bathrooms: 1,
    title: {
      en: 'One-Bedroom Apartment 50 m from the Sea — Plazh, Durres',
      ru: 'Квартира 1+1 в 50 м от моря — район Пляж, Дуррес',
      uk: 'Квартира 1+1 за 50 м від моря — район Пляж, Дуррес',
      sq: 'Apartament 1+1, 50 m nga deti — Plazh, Durrës',
      it: 'Appartamento 1+1 a 50 m dal mare — Plazh, Durazzo',
      pl: 'Mieszkanie 1+1, 50 m od morza — Plazh, Durres',
    },
    shortDescription: {
      en: 'Renovated one-bedroom apartment fifty metres from the sea in Plazh, Durres. Fourth floor with a lift, furnished and ready to use.',
      ru: 'Квартира 1+1 с новым ремонтом в пятидесяти метрах от моря, район Пляж в Дурресе. Четвёртый этаж с лифтом, с мебелью, готова к использованию.',
      uk: 'Квартира 1+1 із новим ремонтом за пʼятдесят метрів від моря, район Пляж у Дурресі. Четвертий поверх із ліфтом, з меблями, готова до використання.',
      sq: 'Apartament 1+1 i rinovuar pesëdhjetë metra nga deti, në Plazh, Durrës. Kati i katërt me ashensor, i mobiluar dhe gati për përdorim.',
      it: 'Appartamento 1+1 ristrutturato a cinquanta metri dal mare, a Plazh, Durazzo. Quarto piano con ascensore, arredato e pronto all’uso.',
      pl: 'Wyremontowane mieszkanie 1+1 pięćdziesiąt metrów od morza, w Plazh w Durres. Czwarte piętro z windą, umeblowane i gotowe do użytku.',
    },
    description: {
      en: 'A one-bedroom apartment in Plazh, the beach district of Durres, fifty metres from the water. The building has a lift and the flat is on the fourth floor.\n\nThe certificate area is 38.5 m²; the total area is 44 m².\n\nIt has been recently renovated and comes with furniture and modern appliances, so it can be used immediately — as a home, a holiday flat, or a rental.\n\nPlazh keeps its infrastructure open all year: shops, supermarkets, restaurants, the promenade and the sandy beach are all within walking distance, which is what makes the district hold its rental demand outside the season.',
      ru: 'Квартира 1+1 в районе Пляж в Дурресе, в пятидесяти метрах от воды. В доме есть лифт, квартира на четвёртом этаже.\n\nПлощадь по сертификату — 38,5 м², общая — 44 м².\n\nСделан свежий ремонт, есть мебель и современная техника, так что пользоваться можно сразу — жить, приезжать на отдых или сдавать.\n\nПляж — район с круглогодичной инфраструктурой: магазины, супермаркеты, рестораны, набережная и песчаный пляж в пешей доступности. Именно поэтому здесь сохраняется спрос на аренду и вне сезона.',
      uk: 'Квартира 1+1 у районі Пляж у Дурресі, за пʼятдесят метрів від води. У будинку є ліфт, квартира на четвертому поверсі.\n\nПлоща за сертифікатом — 38,5 м², загальна — 44 м².\n\nЗроблено свіжий ремонт, є меблі й сучасна техніка, тож користуватися можна одразу — жити, приїжджати на відпочинок або здавати.\n\nПляж — район із цілорічною інфраструктурою: магазини, супермаркети, ресторани, набережна й піщаний пляж у пішій доступності. Саме тому тут зберігається попит на оренду й поза сезоном.',
      sq: 'Apartament 1+1 në Plazh, zona bregdetare e Durrësit, pesëdhjetë metra nga uji. Pallati ka ashensor dhe apartamenti ndodhet në katin e katërt.\n\nSipërfaqja sipas certifikatës është 38,5 m², ndërsa sipërfaqja e përgjithshme 44 m².\n\nËshtë rinovuar së fundmi dhe vjen me mobilie e pajisje moderne, prandaj mund të përdoret menjëherë — për banim, për pushime ose me qira.\n\nPlazhi e mban infrastrukturën të hapur gjatë gjithë vitit: dyqane, supermarkete, restorante, shëtitorja dhe plazhi me rërë janë të gjitha në këmbë. Pikërisht kjo e mban kërkesën për qira edhe jashtë sezonit.',
      it: 'Appartamento 1+1 a Plazh, il quartiere balneare di Durazzo, a cinquanta metri dall’acqua. L’edificio ha l’ascensore e l’appartamento si trova al quarto piano.\n\nLa superficie da certificato è di 38,5 m², quella totale di 44 m².\n\nÈ stato ristrutturato di recente ed è dotato di mobili ed elettrodomestici moderni, quindi è utilizzabile da subito — come casa, appartamento per le vacanze o da affittare.\n\nPlazh mantiene i servizi aperti tutto l’anno: negozi, supermercati, ristoranti, il lungomare e la spiaggia di sabbia sono tutti a piedi. È questo che tiene alta la domanda di affitti anche fuori stagione.',
      pl: 'Mieszkanie 1+1 w Plazh, nadmorskiej dzielnicy Durres, pięćdziesiąt metrów od wody. Budynek ma windę, a mieszkanie znajduje się na czwartym piętrze.\n\nPowierzchnia według certyfikatu to 38,5 m², całkowita 44 m².\n\nZostało niedawno wyremontowane i ma meble oraz nowoczesny sprzęt, więc można z niego korzystać od razu — do mieszkania, na wakacje lub pod wynajem.\n\nPlazh działa przez cały rok: sklepy, supermarkety, restauracje, promenada i piaszczysta plaża są w zasięgu spaceru. To właśnie utrzymuje popyt na najem także poza sezonem.',
    },
    address: {
      en: 'Plazh (Durres Beach), Durres',
      ru: 'Район Пляж, Дуррес',
      uk: 'Район Пляж, Дуррес',
      sq: 'Plazh, Durrës',
      it: 'Plazh, Durazzo',
      pl: 'Plazh, Durres',
    },
    offers: [
      {
        iconKey: 'waves',
        title: {
          en: '50 m from the sea',
          ru: '50 м до моря',
          uk: '50 м до моря',
          sq: '50 m nga deti',
          it: '50 m dal mare',
          pl: '50 m od morza',
        },
      },
      {
        iconKey: 'elevator',
        title: {
          en: 'Fourth floor, building with a lift',
          ru: 'Четвёртый этаж, дом с лифтом',
          uk: 'Четвертий поверх, будинок із ліфтом',
          sq: 'Kati i katërt, pallat me ashensor',
          it: 'Quarto piano, edificio con ascensore',
          pl: 'Czwarte piętro, budynek z windą',
        },
      },
      {
        iconKey: 'key',
        title: {
          en: 'Recently renovated, furnished',
          ru: 'Свежий ремонт, с мебелью',
          uk: 'Свіжий ремонт, з меблями',
          sq: 'E rinovuar së fundmi, e mobiluar',
          it: 'Ristrutturato di recente, arredato',
          pl: 'Niedawno wyremontowane, umeblowane',
        },
      },
      {
        iconKey: 'building',
        title: {
          en: 'Year-round infrastructure within walking distance',
          ru: 'Круглогодичная инфраструктура в пешей доступности',
          uk: 'Цілорічна інфраструктура в пішій доступності',
          sq: 'Infrastrukturë gjatë gjithë vitit në këmbë',
          it: 'Servizi aperti tutto l’anno a piedi',
          pl: 'Całoroczna infrastruktura w zasięgu spaceru',
        },
      },
    ],
  },

  {
    datoId: 'N2TvGMD3QTelMXKRL_qBuQ',
    slug: 'prodazha-studii-s-panoramnymi-oknami-or-400-m-do-morya-or',
    city: 'durres',
    type: 'studio',
    status: 'sale',
    price: 62000,
    area: 36,
    bedrooms: 1,
    bathrooms: 1,
    title: {
      en: 'Studio with Panoramic Windows, 400 m from the Sea — Durres',
      ru: 'Студия с панорамными окнами, 400 м до моря — Дуррес',
      uk: 'Студія з панорамними вікнами, 400 м до моря — Дуррес',
      sq: 'Studio me dritare panoramike, 400 m nga deti — Durrës',
      it: 'Monolocale con finestre panoramiche, 400 m dal mare — Durazzo',
      pl: 'Kawalerka z panoramicznymi oknami, 400 m od morza — Durres',
    },
    shortDescription: {
      en: 'A 36 m² studio with panoramic windows overlooking palms, in a quiet building with a large car park, 400 metres from the sea.',
      ru: 'Студия 36 м² с панорамными окнами и видом на пальмы, в тихом доме с большой парковкой, в 400 метрах от моря.',
      uk: 'Студія 36 м² з панорамними вікнами та видом на пальми, у тихому будинку з великою парковкою, за 400 метрів від моря.',
      sq: 'Studio 36 m² me dritare panoramike dhe pamje nga palmat, në një pallat të qetë me parking të madh, 400 metra nga deti.',
      it: 'Monolocale di 36 m² con finestre panoramiche affacciate sulle palme, in un edificio tranquillo con ampio parcheggio, a 400 metri dal mare.',
      pl: 'Kawalerka 36 m² z panoramicznymi oknami i widokiem na palmy, w cichym budynku z dużym parkingiem, 400 metrów od morza.',
    },
    description: {
      en: 'A 36 m² studio in Durres, four hundred metres from the sea. Panoramic windows look out over palm trees and make the space bright through the day.\n\nThe building is quiet and well kept, with a large car park in the courtyard.\n\nEverything needed day to day is nearby and open all year: shops, supermarkets, cafés, pharmacies and exchange offices. The flat works equally as a holiday place, a year-round home, or a rental.',
      ru: 'Студия 36 м² в Дурресе, в четырёхстах метрах от моря. Панорамные окна выходят на пальмы и делают пространство светлым в течение всего дня.\n\nДом тихий и ухоженный, во дворе большая парковка.\n\nВсё необходимое — рядом и работает круглый год: магазины, супермаркеты, кафе, аптеки, обменные пункты. Квартира одинаково подходит для отдыха, постоянного проживания и сдачи в аренду.',
      uk: 'Студія 36 м² у Дурресі, за чотириста метрів від моря. Панорамні вікна виходять на пальми й роблять простір світлим упродовж дня.\n\nБудинок тихий і доглянутий, у дворі велика парковка.\n\nУсе потрібне поруч і працює цілий рік: магазини, супермаркети, кафе, аптеки, обмінні пункти. Квартира однаково підходить для відпочинку, постійного проживання та оренди.',
      sq: 'Studio 36 m² në Durrës, katërqind metra nga deti. Dritaret panoramike shohin nga palmat dhe e mbajnë ambientin të ndriçuar gjatë gjithë ditës.\n\nPallati është i qetë dhe i mirëmbajtur, me parking të madh në oborr.\n\nGjithçka e nevojshme është pranë dhe funksionon gjatë gjithë vitit: dyqane, supermarkete, kafene, farmaci dhe këmbimore. Apartamenti i shërben njësoj pushimeve, banimit të përhershëm ose qirasë.',
      it: 'Monolocale di 36 m² a Durazzo, a quattrocento metri dal mare. Le finestre panoramiche affacciano sulle palme e mantengono l’ambiente luminoso per tutta la giornata.\n\nL’edificio è tranquillo e curato, con un ampio parcheggio nel cortile.\n\nTutto il necessario è vicino e aperto tutto l’anno: negozi, supermercati, bar, farmacie e uffici di cambio. L’appartamento funziona sia per le vacanze, sia come casa tutto l’anno, sia in affitto.',
      pl: 'Kawalerka o powierzchni 36 m² w Durres, czterysta metrów od morza. Panoramiczne okna wychodzą na palmy i sprawiają, że wnętrze jest jasne przez cały dzień.\n\nBudynek jest cichy i zadbany, na dziedzińcu duży parking.\n\nWszystko, co potrzebne, jest blisko i czynne przez cały rok: sklepy, supermarkety, kawiarnie, apteki i kantory. Mieszkanie sprawdzi się na wakacje, do życia przez cały rok i pod wynajem.',
    },
    address: {
      en: 'Durres, 400 m from the sea',
      ru: 'Дуррес, 400 м до моря',
      uk: 'Дуррес, 400 м до моря',
      sq: 'Durrës, 400 m nga deti',
      it: 'Durazzo, 400 m dal mare',
      pl: 'Durres, 400 m od morza',
    },
    offers: [
      {
        iconKey: 'sun',
        title: {
          en: 'Panoramic windows, bright all day',
          ru: 'Панорамные окна, светло весь день',
          uk: 'Панорамні вікна, світло весь день',
          sq: 'Dritare panoramike, dritë gjithë ditën',
          it: 'Finestre panoramiche, luminoso tutto il giorno',
          pl: 'Panoramiczne okna, jasno przez cały dzień',
        },
      },
      {
        iconKey: 'parking',
        title: {
          en: 'Large car park in the courtyard',
          ru: 'Большая парковка во дворе',
          uk: 'Велика парковка у дворі',
          sq: 'Parking i madh në oborr',
          it: 'Ampio parcheggio nel cortile',
          pl: 'Duży parking na dziedzińcu',
        },
      },
      {
        iconKey: 'waves',
        title: {
          en: '400 m from the sea',
          ru: '400 м до моря',
          uk: '400 м до моря',
          sq: '400 m nga deti',
          it: '400 m dal mare',
          pl: '400 m od morza',
        },
      },
      {
        iconKey: 'tree',
        title: {
          en: 'Quiet, well-kept building',
          ru: 'Тихий ухоженный дом',
          uk: 'Тихий доглянутий будинок',
          sq: 'Pallat i qetë dhe i mirëmbajtur',
          it: 'Edificio tranquillo e curato',
          pl: 'Cichy, zadbany budynek',
        },
      },
    ],
  },

  {
    datoId: 'VK6uQ8mHR9mzyR_hN-EYdg',
    slug: 'prodazha-vidovoj-kvartiry-11-v-shkembi-kavaya',
    city: 'durres',
    district: 'shkembi-durres',
    type: 'apartment',
    status: 'sale',
    price: 79000,
    area: 52,
    bedrooms: 1,
    bathrooms: 1,
    title: {
      en: 'One-Bedroom Apartment with a View in Shkembi i Kavajes, Durres',
      ru: 'Видовая квартира 1+1 в Шкемби Кавая, Дуррес',
      uk: 'Видова квартира 1+1 у Шкемби Кавая, Дуррес',
      sq: 'Apartament 1+1 me pamje në Shkëmbin e Kavajës, Durrës',
      it: 'Appartamento 1+1 con vista a Shkembi i Kavajes, Durazzo',
      pl: 'Mieszkanie 1+1 z widokiem w Shkembi i Kavajes, Durres',
    },
    shortDescription: {
      en: 'Seventh-floor one-bedroom apartment in Shkembi i Kavajes, two to three minutes on foot from the sea, in a building with a lift.',
      ru: 'Квартира 1+1 на седьмом этаже в Шкемби Кавая, две-три минуты пешком до моря, дом с лифтом.',
      uk: 'Квартира 1+1 на сьомому поверсі у Шкемби Кавая, дві-три хвилини пішки до моря, будинок із ліфтом.',
      sq: 'Apartament 1+1 në katin e shtatë në Shkëmbin e Kavajës, dy-tre minuta në këmbë nga deti, pallat me ashensor.',
      it: 'Appartamento 1+1 al settimo piano a Shkembi i Kavajes, due o tre minuti a piedi dal mare, edificio con ascensore.',
      pl: 'Mieszkanie 1+1 na siódmym piętrze w Shkembi i Kavajes, dwie-trzy minuty pieszo od morza, budynek z windą.',
    },
    description: {
      en: 'A one-bedroom apartment in Shkembi i Kavajes, one of the busiest stretches of the Durres coast. The sea is two to three minutes away on foot.\n\nThe total area is 60 m², of which 52 m² are on the certificate. The flat is on the seventh floor of a building with a lift.\n\nThe layout is straightforward and works well: a living room with a kitchen, a separate bedroom and a bathroom.\n\nThe area is still developing, with shops, supermarkets, cafés, restaurants, hotels and the promenade nearby. Demand for seasonal rentals here is high, which is the main reason the district is bought into.',
      ru: 'Квартира 1+1 в Шкемби Кавая — одном из самых оживлённых участков побережья Дурреса. До моря две-три минуты пешком.\n\nОбщая площадь — 60 м², из них 52 м² по сертификату. Квартира на седьмом этаже, в доме есть лифт.\n\nПланировка простая и рабочая: гостиная с кухней, отдельная спальня, санузел.\n\nРайон продолжает развиваться: рядом магазины, супермаркеты, кафе, рестораны, отели и набережная. Спрос на сезонную аренду здесь высокий — именно поэтому район и покупают.',
      uk: 'Квартира 1+1 у Шкемби Кавая — одній із найжвавіших ділянок узбережжя Дурреса. До моря дві-три хвилини пішки.\n\nЗагальна площа — 60 м², з них 52 м² за сертифікатом. Квартира на сьомому поверсі, у будинку є ліфт.\n\nПланування просте й робоче: вітальня з кухнею, окрема спальня, санвузол.\n\nРайон продовжує розвиватися: поруч магазини, супермаркети, кафе, ресторани, готелі й набережна. Попит на сезонну оренду тут високий — саме тому район і купують.',
      sq: 'Apartament 1+1 në Shkëmbin e Kavajës, një nga pjesët më të frekuentuara të bregdetit të Durrësit. Deti është dy-tre minuta në këmbë.\n\nSipërfaqja e përgjithshme është 60 m², nga të cilat 52 m² sipas certifikatës. Apartamenti ndodhet në katin e shtatë, në pallat me ashensor.\n\nPlanimetria është e thjeshtë dhe funksionale: dhomë ndenjeje me kuzhinë, dhomë gjumi më vete dhe tualet.\n\nZona vazhdon të zhvillohet: pranë ka dyqane, supermarkete, kafene, restorante, hotele dhe shëtitoren. Kërkesa për qira sezonale këtu është e lartë — pikërisht për këtë blihet kjo zonë.',
      it: 'Appartamento 1+1 a Shkembi i Kavajes, uno dei tratti più frequentati della costa di Durazzo. Il mare è a due o tre minuti a piedi.\n\nLa superficie totale è di 60 m², di cui 52 m² da certificato. L’appartamento è al settimo piano, in un edificio con ascensore.\n\nLa distribuzione è semplice e funziona bene: soggiorno con cucina, camera da letto separata e bagno.\n\nLa zona continua a svilupparsi: nelle vicinanze negozi, supermercati, bar, ristoranti, hotel e il lungomare. La domanda di affitti stagionali è alta, ed è la ragione principale per cui si compra qui.',
      pl: 'Mieszkanie 1+1 w Shkembi i Kavajes, jednym z najbardziej ruchliwych odcinków wybrzeża Durres. Do morza dwie-trzy minuty pieszo.\n\nPowierzchnia całkowita to 60 m², z czego 52 m² według certyfikatu. Mieszkanie jest na siódmym piętrze, budynek ma windę.\n\nUkład jest prosty i funkcjonalny: salon z kuchnią, osobna sypialnia i łazienka.\n\nDzielnica wciąż się rozwija: w pobliżu sklepy, supermarkety, kawiarnie, restauracje, hotele i promenada. Popyt na najem sezonowy jest tu wysoki i to główny powód, dla którego kupuje się w tej okolicy.',
    },
    address: {
      en: 'Shkembi i Kavajes, Durres',
      ru: 'Шкемби Кавая, Дуррес',
      uk: 'Шкемби Кавая, Дуррес',
      sq: 'Shkëmbi i Kavajës, Durrës',
      it: 'Shkembi i Kavajes, Durazzo',
      pl: 'Shkembi i Kavajes, Durres',
    },
    offers: [
      {
        iconKey: 'waves',
        title: {
          en: '2–3 minutes on foot to the sea',
          ru: '2–3 минуты пешком до моря',
          uk: '2–3 хвилини пішки до моря',
          sq: '2–3 minuta në këmbë nga deti',
          it: '2–3 minuti a piedi dal mare',
          pl: '2–3 minuty pieszo do morza',
        },
      },
      {
        iconKey: 'elevator',
        title: {
          en: 'Seventh floor, building with a lift',
          ru: 'Седьмой этаж, дом с лифтом',
          uk: 'Сьомий поверх, будинок із ліфтом',
          sq: 'Kati i shtatë, pallat me ashensor',
          it: 'Settimo piano, edificio con ascensore',
          pl: 'Siódme piętro, budynek z windą',
        },
      },
      {
        iconKey: 'layout',
        title: {
          en: 'Separate bedroom, living room with kitchen',
          ru: 'Отдельная спальня, гостиная с кухней',
          uk: 'Окрема спальня, вітальня з кухнею',
          sq: 'Dhomë gjumi më vete, ndenjë me kuzhinë',
          it: 'Camera separata, soggiorno con cucina',
          pl: 'Osobna sypialnia, salon z kuchnią',
        },
      },
      {
        iconKey: 'building',
        title: {
          en: 'Established tourist district with high seasonal demand',
          ru: 'Востребованный туристический район, высокий сезонный спрос',
          uk: 'Затребуваний туристичний район, високий сезонний попит',
          sq: 'Zonë turistike e kërkuar, kërkesë e lartë sezonale',
          it: 'Zona turistica affermata, alta domanda stagionale',
          pl: 'Uznana dzielnica turystyczna, wysoki popyt sezonowy',
        },
      },
    ],
  },
]
