import type {PropertyContent} from './types'

/** Objects 17–22: Golem new build, budget Plazh 1+1, Saranda investment house, Durres family house, seafront hotel, Vlore 1+1. */
export const BATCH_4: PropertyContent[] = [
  {
    datoId: 'PyDrTzNpQOCuTZro3LkCpg',
    slug: 'novyy-6-etazhnyy-dom-v-goleme-ryadom-s-morem',
    city: 'durres',
    district: 'golem-durres',
    type: 'apartment',
    status: 'sale',
    // Dato stores 1300 in `price`, but the source text is explicit that this is
    // €1,300 per m², not the price of a flat. 62 m² × €1,300 = €80,600, and the
    // per-m² figure is stated in the description so nobody is misled.
    price: 80600,
    area: 62,
    bedrooms: 1,
    bathrooms: 1,
    title: {
      en: 'Apartments in a New Building in Golem, 200–250 m from the Sea',
      ru: 'Квартиры в новом доме в Големе, 200–250 м до моря',
      uk: 'Квартири в новому будинку в Големі, 200–250 м до моря',
      sq: 'Apartamente në një pallat të ri në Golem, 200–250 m nga deti',
      it: 'Appartamenti in un nuovo edificio a Golem, 200–250 m dal mare',
      pl: 'Mieszkania w nowym budynku w Golem, 200–250 m od morza',
    },
    shortDescription: {
      en: 'Apartments in a new six-storey building in Golem, 200–250 metres from the sea, at €1,300 per m². Completion spring–summer 2026.',
      ru: 'Квартиры в новом шестиэтажном доме в Големе, в 200–250 метрах от моря, по 1300 € за м². Сдача — весна-лето 2026 года.',
      uk: 'Квартири в новому шестиповерховому будинку в Големі, за 200–250 метрів від моря, по 1300 € за м². Здача — весна-літо 2026 року.',
      sq: 'Apartamente në një pallat të ri gjashtëkatësh në Golem, 200–250 metra nga deti, me 1.300 € për m². Dorëzimi pranverë-verë 2026.',
      it: 'Appartamenti in un nuovo edificio di sei piani a Golem, a 200–250 metri dal mare, a 1.300 € al m². Consegna primavera-estate 2026.',
      pl: 'Mieszkania w nowym sześciopiętrowym budynku w Golem, 200–250 metrów od morza, po 1300 € za m². Oddanie wiosna-lato 2026.',
    },
    description: {
      en: 'A new six-storey residential building in Golem, Durres, in a quiet green part of the district, 200–250 metres from the sea. Completion is planned for spring–summer 2026.\n\nFive apartments are available, on the second, third and fourth floors, in different layouts and sizes. The price is €1,300 per square metre, so the total depends on the unit chosen.\n\nThe building is constructed with M400 high-strength concrete, hollow red ceramic blocks of 25×25×25 cm and steel structural elements.\n\nThe location is calm, which suits both living here and letting.',
      ru: 'Новый шестиэтажный жилой дом в Големе, Дуррес, в тихой зелёной части района, в 200–250 метрах от моря. Сдача запланирована на весну-лето 2026 года.\n\nВ продаже пять квартир — на втором, третьем и четвёртом этажах, с разными планировками и метражами. Цена — 1300 € за квадратный метр, поэтому итоговая сумма зависит от выбранной квартиры.\n\nДом построен с использованием высокопрочного бетона марки М400, красных керамических пустотелых блоков 25×25×25 см и металлических конструктивных элементов.\n\nЛокация спокойная — подходит и для жизни, и для сдачи в аренду.',
      uk: 'Новий шестиповерховий житловий будинок у Големі, Дуррес, у тихій зеленій частині району, за 200–250 метрів від моря. Здача запланована на весну-літо 2026 року.\n\nУ продажу пʼять квартир — на другому, третьому та четвертому поверхах, із різними плануваннями й метражами. Ціна — 1300 € за квадратний метр, тож підсумкова сума залежить від обраної квартири.\n\nБудинок зведено з використанням високоміцного бетону марки М400, червоних керамічних порожнистих блоків 25×25×25 см і металевих конструктивних елементів.\n\nЛокація спокійна — підходить і для життя, і для оренди.',
      sq: 'Pallat i ri banimi me gjashtë kate në Golem, Durrës, në një pjesë të qetë dhe të gjelbër të zonës, 200–250 metra nga deti. Dorëzimi parashikohet në pranverë-verë 2026.\n\nJanë në shitje pesë apartamente — në katin e dytë, të tretë dhe të katërt, me planimetri dhe sipërfaqe të ndryshme. Çmimi është 1.300 € për metër katror, prandaj shuma përfundimtare varet nga njësia e zgjedhur.\n\nNdërtesa është ngritur me beton me rezistencë të lartë M400, tulla qeramike të kuqe të zbrazëta 25×25×25 cm dhe elemente strukturore metalike.\n\nVendndodhja është e qetë dhe i shërben si banimit, ashtu edhe qirasë.',
      it: 'Nuovo edificio residenziale di sei piani a Golem, Durazzo, in una zona tranquilla e verde del quartiere, a 200–250 metri dal mare. La consegna è prevista per la primavera-estate 2026.\n\nSono disponibili cinque appartamenti, al secondo, terzo e quarto piano, con distribuzioni e metrature diverse. Il prezzo è di 1.300 € al metro quadro, quindi l’importo finale dipende dall’unità scelta.\n\nL’edificio è realizzato con calcestruzzo ad alta resistenza M400, blocchi ceramici rossi forati da 25×25×25 cm ed elementi strutturali in acciaio.\n\nLa posizione è tranquilla e si presta sia all’abitare sia all’affitto.',
      pl: 'Nowy sześciopiętrowy budynek mieszkalny w Golem, Durres, w cichej i zielonej części dzielnicy, 200–250 metrów od morza. Oddanie planowane na wiosnę-lato 2026 roku.\n\nW sprzedaży jest pięć mieszkań — na drugim, trzecim i czwartym piętrze, o różnych układach i metrażach. Cena wynosi 1300 € za metr kwadratowy, więc kwota końcowa zależy od wybranego lokalu.\n\nBudynek powstał z użyciem betonu wysokiej wytrzymałości M400, czerwonych ceramicznych pustaków 25×25×25 cm oraz stalowych elementów konstrukcyjnych.\n\nLokalizacja jest spokojna i sprawdza się zarówno do mieszkania, jak i pod wynajem.',
    },
    address: {
      en: 'Golem, Durres',
      ru: 'Голем, Дуррес',
      uk: 'Голем, Дуррес',
      sq: 'Golem, Durrës',
      it: 'Golem, Durazzo',
      pl: 'Golem, Durres',
    },
    offers: [
      {
        iconKey: 'building',
        title: {
          en: 'New build, completion spring–summer 2026',
          ru: 'Новостройка, сдача весна-лето 2026',
          uk: 'Новобудова, здача весна-літо 2026',
          sq: 'Ndërtim i ri, dorëzim pranverë-verë 2026',
          it: 'Nuova costruzione, consegna primavera-estate 2026',
          pl: 'Nowy budynek, oddanie wiosna-lato 2026',
        },
      },
      {
        iconKey: 'waves',
        title: {
          en: '200–250 m from the sea',
          ru: '200–250 м до моря',
          uk: '200–250 м до моря',
          sq: '200–250 m nga deti',
          it: '200–250 m dal mare',
          pl: '200–250 m od morza',
        },
      },
      {
        iconKey: 'layout',
        title: {
          en: 'Five units on floors 2–4, different sizes',
          ru: 'Пять квартир на 2–4 этажах, разные метражи',
          uk: 'Пʼять квартир на 2–4 поверхах, різні метражі',
          sq: 'Pesë njësi në katet 2–4, me sipërfaqe të ndryshme',
          it: 'Cinque unità ai piani 2–4, metrature diverse',
          pl: 'Pięć lokali na piętrach 2–4, różne metraże',
        },
      },
      {
        iconKey: 'shield',
        title: {
          en: 'M400 concrete and steel structural elements',
          ru: 'Бетон М400 и металлические конструктивные элементы',
          uk: 'Бетон М400 та металеві конструктивні елементи',
          sq: 'Beton M400 dhe elemente strukturore metalike',
          it: 'Calcestruzzo M400 ed elementi strutturali in acciaio',
          pl: 'Beton M400 i stalowe elementy konstrukcyjne',
        },
      },
      {
        iconKey: 'tree',
        title: {
          en: 'Quiet, green part of Golem',
          ru: 'Тихая зелёная часть Голема',
          uk: 'Тиха зелена частина Голема',
          sq: 'Pjesë e qetë dhe e gjelbër e Golemit',
          it: 'Zona tranquilla e verde di Golem',
          pl: 'Cicha, zielona część Golem',
        },
      },
    ],
    review:
      'PRICE NEEDS CONFIRMATION. Dato has price=1300, which the source text shows is €1,300/m², not a unit price. Set here to 80,600 € (62 m² × 1,300) and the per-m² figure is stated in the copy. Also: this is one listing standing for five different units — consider splitting it into five records once sizes are known. Partner Telegram and WhatsApp contacts removed from the source text.',
  },

  {
    datoId: 'QiCuEFi4Ryu4INM6mbVAdg',
    slug: 'byudzhetnaya-kvartira-1-1-v-horoshey-lokacii',
    city: 'durres',
    district: 'plazh',
    type: 'apartment',
    status: 'sale',
    price: 65000,
    area: 49,
    bedrooms: 1,
    bathrooms: 1,
    title: {
      en: 'Affordable One-Bedroom Apartment 300 m from the Beach — Plazh, Durres',
      ru: 'Бюджетная квартира 1+1 в 300 м от пляжа — Пляж, Дуррес',
      uk: 'Бюджетна квартира 1+1 за 300 м від пляжу — Пляж, Дуррес',
      sq: 'Apartament 1+1 me çmim të përballueshëm, 300 m nga plazhi — Plazh, Durrës',
      it: 'Appartamento 1+1 economico a 300 m dalla spiaggia — Plazh, Durazzo',
      pl: 'Niedrogie mieszkanie 1+1, 300 m od plaży — Plazh, Durres',
    },
    shortDescription: {
      en: 'A 49 m² one-bedroom apartment on the seventh floor in Plazh, three hundred metres from the beach, at one of the lower prices in the district.',
      ru: 'Квартира 1+1 площадью 49 м² на седьмом этаже в районе Пляж, в трёхстах метрах от пляжа, по одной из низких цен в районе.',
      uk: 'Квартира 1+1 площею 49 м² на сьомому поверсі в районі Пляж, за триста метрів від пляжу, за однією з низьких цін у районі.',
      sq: 'Apartament 1+1 me sipërfaqe 49 m² në katin e shtatë në Plazh, treqind metra nga plazhi, me një nga çmimet më të ulëta në zonë.',
      it: 'Appartamento 1+1 di 49 m² al settimo piano a Plazh, a trecento metri dalla spiaggia, a uno dei prezzi più bassi della zona.',
      pl: 'Mieszkanie 1+1 o powierzchni 49 m² na siódmym piętrze w Plazh, trzysta metrów od plaży, w jednej z niższych cen w dzielnicy.',
    },
    description: {
      en: 'A one-bedroom apartment of 49 m² by certificate in Plazh, Durres, three hundred metres from the beach. Seventh floor, in a building with a lift.\n\nThis is one of the more affordable options in a district that stays busy year-round, which is the main argument for it. The furniture and appliances can be replaced to taste — that is reflected in the price.\n\nIt works as a first home by the sea or as a rental purchase.',
      ru: 'Квартира 1+1 площадью 49 м² по сертификату в районе Пляж, Дуррес, в трёхстах метрах от пляжа. Седьмой этаж, дом с лифтом.\n\nЭто один из более доступных вариантов в районе, который остаётся оживлённым круглый год, — в этом и главный аргумент. Мебель и технику можно обновить под себя, что и заложено в цену.\n\nПодходит как первое жильё у моря или как покупка под аренду.',
      uk: 'Квартира 1+1 площею 49 м² за сертифікатом у районі Пляж, Дуррес, за триста метрів від пляжу. Сьомий поверх, будинок із ліфтом.\n\nЦе один із доступніших варіантів у районі, який залишається жвавим цілий рік, — у цьому й головний аргумент. Меблі й техніку можна оновити під себе, що й закладено в ціну.\n\nПідходить як перше житло біля моря або як купівля під оренду.',
      sq: 'Apartament 1+1 me 49 m² sipas certifikatës në Plazh, Durrës, treqind metra nga plazhi. Kati i shtatë, në pallat me ashensor.\n\nKy është një nga variantet më të përballueshme në një zonë që mbetet aktive gjatë gjithë vitit — dhe pikërisht ky është argumenti kryesor. Mobiliet dhe pajisjet mund të rinovohen sipas shijes, gjë që reflektohet në çmim.\n\nI shërben si banesa e parë pranë detit ose si blerje për qira.',
      it: 'Appartamento 1+1 di 49 m² da certificato a Plazh, Durazzo, a trecento metri dalla spiaggia. Settimo piano, in un edificio con ascensore.\n\nÈ una delle opzioni più accessibili in un quartiere che resta vivo tutto l’anno, ed è questo l’argomento principale. Mobili ed elettrodomestici possono essere rinnovati secondo il gusto, cosa che si riflette nel prezzo.\n\nFunziona come prima casa al mare o come acquisto da mettere a reddito.',
      pl: 'Mieszkanie 1+1 o powierzchni 49 m² według certyfikatu w Plazh, Durres, trzysta metrów od plaży. Siódme piętro, budynek z windą.\n\nTo jedna z tańszych opcji w dzielnicy, która pozostaje żywa przez cały rok — i to jest główny argument. Meble i sprzęt można wymienić według własnego gustu, co uwzględnia cena.\n\nSprawdzi się jako pierwsze mieszkanie nad morzem albo zakup pod wynajem.',
    },
    address: {
      en: 'Plazh (Durres Beach), Durres',
      ru: 'Район Пляж, Дуррес',
      uk: 'Район Пляж, Дуррес',
      sq: 'Plazh, Durrës',
      it: 'Plazh, Durazzo',
      pl: 'Plazh, Durres',
    },
    offers: [
      {
        iconKey: 'waves',
        title: {
          en: '300 m from the beach',
          ru: '300 м до пляжа',
          uk: '300 м до пляжу',
          sq: '300 m nga plazhi',
          it: '300 m dalla spiaggia',
          pl: '300 m od plaży',
        },
      },
      {
        iconKey: 'elevator',
        title: {
          en: 'Seventh floor, building with a lift',
          ru: 'Седьмой этаж, дом с лифтом',
          uk: 'Сьомий поверх, будинок із ліфтом',
          sq: 'Kati i shtatë, pallat me ashensor',
          it: 'Settimo piano, edificio con ascensore',
          pl: 'Siódme piętro, budynek z windą',
        },
      },
      {
        iconKey: 'building',
        title: {
          en: 'Established district, active all year',
          ru: 'Обжитой район, активен круглый год',
          uk: 'Обжитий район, активний цілий рік',
          sq: 'Zonë e konsoliduar, aktive gjatë gjithë vitit',
          it: 'Quartiere consolidato, attivo tutto l’anno',
          pl: 'Zadomowiona dzielnica, czynna przez cały rok',
        },
      },
    ],
  },

  {
    datoId: 'Ja1vXq5_TrqO_H-E6bjh1A',
    slug: 'prodazha-novostroya-investicionnyy-obekt-v-sarande',
    city: 'sarande',
    type: 'apartment',
    status: 'sale',
    price: 193050,
    area: 117,
    bedrooms: 2,
    bathrooms: 1,
    title: {
      en: 'New Building with Four Two-Bedroom Apartments — Saranda',
      ru: 'Новый дом с четырьмя квартирами 2+1 — Саранда',
      uk: 'Новий будинок із чотирма квартирами 2+1 — Саранда',
      sq: 'Ndërtesë e re me katër apartamente 2+1 — Sarandë',
      it: 'Nuovo edificio con quattro appartamenti 2+1 — Saranda',
      pl: 'Nowy budynek z czterema mieszkaniami 2+1 — Saranda',
    },
    shortDescription: {
      en: 'A new four-storey building in Saranda with one two-bedroom apartment per floor, sold whole or floor by floor. Documents complete.',
      ru: 'Новый четырёхэтажный дом в Саранде: по одной квартире 2+1 на этаже, продаётся целиком или поэтажно. Документы готовы.',
      uk: 'Новий чотириповерховий будинок у Саранді: по одній квартирі 2+1 на поверсі, продається цілком або поверхово. Документи готові.',
      sq: 'Ndërtesë e re katërkatëshe në Sarandë: një apartament 2+1 për kat, shitet e plotë ose kat pas kati. Dokumentet të gatshme.',
      it: 'Nuovo edificio di quattro piani a Saranda: un appartamento 2+1 per piano, in vendita per intero o piano per piano. Documenti completi.',
      pl: 'Nowy czteropiętrowy budynek w Sarandzie: po jednym mieszkaniu 2+1 na piętrze, sprzedawany w całości lub piętrami. Dokumenty gotowe.',
    },
    description: {
      en: 'A new building in Saranda with four floors and one two-bedroom apartment on each. Each apartment measures 117 m² in total, 93 m² on the certificate.\n\nThe layout of each is a spacious living room with a kitchen, two bedrooms, a bathroom and a balcony. The upper floors have a panoramic sea view.\n\nThe building is new construction with a complete set of documents, in a quiet area not far from the sea and from the town centre.\n\nIt can be bought whole — which suits a small hotel, a set of rental apartments or a family project — or one floor at a time.',
      ru: 'Новый дом в Саранде: четыре этажа, на каждом по одной квартире 2+1. Площадь каждой — 117 м² общая, 93 м² по сертификату.\n\nПланировка каждой: просторная гостиная с кухней, две спальни, ванная комната и балкон. С верхних этажей открывается панорамный вид на море.\n\nДом — новострой с полным пакетом документов, расположен в спокойном районе недалеко от моря и центра города.\n\nМожно купить целиком — под мини-отель, апартаменты под аренду или семейный проект — либо приобретать поэтажно.',
      uk: 'Новий будинок у Саранді: чотири поверхи, на кожному по одній квартирі 2+1. Площа кожної — 117 м² загальна, 93 м² за сертифікатом.\n\nПланування кожної: простора вітальня з кухнею, дві спальні, ванна кімната й балкон. З верхніх поверхів відкривається панорамний вид на море.\n\nБудинок — новобудова з повним пакетом документів, розташований у спокійному районі неподалік від моря й центру міста.\n\nМожна придбати цілком — під міні-готель, апартаменти під оренду або сімейний проєкт — або купувати поверхово.',
      sq: 'Ndërtesë e re në Sarandë: katër kate, me nga një apartament 2+1 në secilin. Sipërfaqja e secilit është 117 m² gjithsej, 93 m² sipas certifikatës.\n\nPlanimetria e secilit: ndenjë e gjerë me kuzhinë, dy dhoma gjumi, banjë dhe ballkon. Nga katet e sipërme hapet pamje panoramike nga deti.\n\nNdërtesa është e re, me dokumentacion të plotë, në një zonë të qetë jo larg detit dhe qendrës së qytetit.\n\nMund të blihet e tëra — e përshtatshme për një hotel të vogël, apartamente me qira ose një projekt familjar — ose kat pas kati.',
      it: 'Nuovo edificio a Saranda: quattro piani, con un appartamento 2+1 per piano. Ciascun appartamento misura 117 m² totali, 93 m² da certificato.\n\nLa distribuzione di ognuno prevede un ampio soggiorno con cucina, due camere, un bagno e un balcone. Dai piani alti si gode una vista panoramica sul mare.\n\nL’edificio è di nuova costruzione con documentazione completa, in una zona tranquilla non lontana dal mare e dal centro.\n\nSi può acquistare per intero — adatto a un piccolo hotel, ad appartamenti da affittare o a un progetto familiare — oppure un piano alla volta.',
      pl: 'Nowy budynek w Sarandzie: cztery piętra, na każdym po jednym mieszkaniu 2+1. Powierzchnia każdego to 117 m² łącznie, 93 m² według certyfikatu.\n\nUkład każdego: przestronny salon z kuchnią, dwie sypialnie, łazienka i balkon. Z wyższych pięter roztacza się panoramiczny widok na morze.\n\nBudynek jest nowy, z kompletem dokumentów, w spokojnej okolicy niedaleko morza i centrum miasta.\n\nMożna kupić go w całości — pod mały hotel, apartamenty na wynajem lub projekt rodzinny — albo piętro po piętrze.',
    },
    address: {
      en: 'Saranda, quiet area near the sea and the town centre',
      ru: 'Саранда, спокойный район недалеко от моря и центра',
      uk: 'Саранда, спокійний район неподалік від моря й центру',
      sq: 'Sarandë, zonë e qetë pranë detit dhe qendrës',
      it: 'Saranda, zona tranquilla vicino al mare e al centro',
      pl: 'Saranda, spokojna okolica blisko morza i centrum',
    },
    offers: [
      {
        iconKey: 'building',
        title: {
          en: 'New build, four floors, one apartment each',
          ru: 'Новострой, четыре этажа, по квартире на этаж',
          uk: 'Новобудова, чотири поверхи, по квартирі на поверх',
          sq: 'Ndërtim i ri, katër kate, një apartament për kat',
          it: 'Nuova costruzione, quattro piani, un appartamento ciascuno',
          pl: 'Nowy budynek, cztery piętra, po jednym mieszkaniu',
        },
      },
      {
        iconKey: 'shield',
        title: {
          en: 'Complete set of documents',
          ru: 'Полный пакет документов',
          uk: 'Повний пакет документів',
          sq: 'Dokumentacion i plotë',
          it: 'Documentazione completa',
          pl: 'Komplet dokumentów',
        },
      },
      {
        iconKey: 'key',
        title: {
          en: 'Buy the whole building or a single floor',
          ru: 'Можно купить дом целиком или один этаж',
          uk: 'Можна купити будинок цілком або один поверх',
          sq: 'Blihet e tëra ose vetëm një kat',
          it: 'Acquistabile per intero o un solo piano',
          pl: 'Zakup całego budynku lub jednego piętra',
        },
      },
      {
        iconKey: 'waves',
        title: {
          en: 'Panoramic sea view from the upper floors',
          ru: 'Панорамный вид на море с верхних этажей',
          uk: 'Панорамний вид на море з верхніх поверхів',
          sq: 'Pamje panoramike nga deti nga katet e sipërme',
          it: 'Vista panoramica sul mare dai piani alti',
          pl: 'Panoramiczny widok na morze z wyższych pięter',
        },
      },
    ],
    review:
      'Price 193,050 € corresponds to one apartment. The whole building is also available — confirm whether a separate record is wanted for the building as a unit.',
  },

  {
    datoId: 'aMm7A6dISv-TR9MAXRt0yA',
    slug: 'prodaetsya-bolshoy-semeynyy-dom-v-durrese',
    city: 'durres',
    type: 'house',
    status: 'sale',
    price: 350000,
    area: 400,
    bedrooms: 6,
    bathrooms: 4,
    title: {
      en: 'Large Family House 400 m² with a Garden — Durres',
      ru: 'Большой семейный дом 400 м² с садом — Дуррес',
      uk: 'Великий сімейний будинок 400 м² із садом — Дуррес',
      sq: 'Shtëpi e madhe familjare 400 m² me kopsht — Durrës',
      it: 'Grande casa familiare di 400 m² con giardino — Durazzo',
      pl: 'Duży dom rodzinny 400 m² z ogrodem — Durres',
    },
    shortDescription: {
      en: 'A 400 m² house on a 1,000 m² plot in a quiet green part of Durres, with two living floors, four bathrooms and separate guest studios.',
      ru: 'Дом 400 м² на участке 10 соток в тихой зелёной части Дурреса: два жилых этажа, четыре санузла и отдельные студии для гостей.',
      uk: 'Будинок 400 м² на ділянці 10 соток у тихій зеленій частині Дурреса: два житлові поверхи, чотири санвузли та окремі студії для гостей.',
      sq: 'Shtëpi 400 m² në një truall prej 1.000 m² në një pjesë të qetë e të gjelbër të Durrësit: dy kate banimi, katër tualete dhe studio të veçanta për mysafirë.',
      it: 'Casa di 400 m² su un terreno di 1.000 m² in una zona verde e tranquilla di Durazzo: due piani abitativi, quattro bagni e monolocali separati per gli ospiti.',
      pl: 'Dom 400 m² na działce 1000 m² w cichej, zielonej części Durres: dwie kondygnacje mieszkalne, cztery łazienki i osobne studia dla gości.',
    },
    description: {
      en: 'A house of 400 m² on a plot of 1,000 m², in a quiet green part of Durres. It suits one large family, or two, and anyone who wants space and privacy.\n\nThere are two living floors with a number of large rooms and four bathrooms, finished to a modern standard.\n\nSeparate studio outbuildings on the plot can house guests or be let.\n\nThe garden is large and well kept, which is what gives the property its character: city convenience with a green corner of your own near the sea.',
      ru: 'Дом площадью 400 м² на участке в 10 соток, в тихой зелёной части Дурреса. Подходит для одной большой семьи или для двух, а также для тех, кто ценит простор и уединение.\n\nДва жилых этажа, много просторных комнат и четыре санузла, отделка современная и качественная.\n\nНа участке есть отдельные постройки-студии — под гостей или под сдачу.\n\nСад большой и ухоженный, и именно он задаёт характер объекта: удобство города и собственный зелёный уголок у моря.',
      uk: 'Будинок площею 400 м² на ділянці 10 соток, у тихій зеленій частині Дурреса. Підходить для однієї великої родини або для двох, а також для тих, хто цінує простір і усамітнення.\n\nДва житлові поверхи, багато просторих кімнат і чотири санвузли, оздоблення сучасне та якісне.\n\nНа ділянці є окремі будівлі-студії — під гостей або під оренду.\n\nСад великий і доглянутий, і саме він задає характер обʼєкта: зручність міста й власний зелений куточок біля моря.',
      sq: 'Shtëpi me sipërfaqe 400 m² në një truall prej 1.000 m², në një pjesë të qetë dhe të gjelbër të Durrësit. I përshtatet një familjeje të madhe ose dyve, si dhe kujtdo që kërkon hapësirë e qetësi.\n\nKa dy kate banimi me shumë dhoma të gjera dhe katër tualete, me përfundim modern dhe cilësor.\n\nNë truall ndodhen edhe ndërtesa të veçanta studio — për mysafirë ose për qira.\n\nKopshti është i madh dhe i mirëmbajtur, dhe pikërisht ai i jep karakter pronës: rehatia e qytetit bashkë me një cep të gjelbër pranë detit.',
      it: 'Casa di 400 m² su un terreno di 1.000 m², in una zona verde e tranquilla di Durazzo. Adatta a una famiglia numerosa o a due, e a chi cerca spazio e riservatezza.\n\nDue piani abitativi con numerose stanze ampie e quattro bagni, con finiture moderne e di qualità.\n\nSul terreno ci sono monolocali indipendenti, utilizzabili per gli ospiti o da affittare.\n\nIl giardino è grande e curato, ed è ciò che dà carattere alla proprietà: la comodità della città con un angolo verde tutto proprio vicino al mare.',
      pl: 'Dom o powierzchni 400 m² na działce 1000 m², w cichej i zielonej części Durres. Nadaje się dla jednej dużej rodziny lub dwóch, a także dla tych, którzy cenią przestrzeń i prywatność.\n\nDwie kondygnacje mieszkalne z wieloma dużymi pokojami i czterema łazienkami, wykończone nowocześnie i solidnie.\n\nNa działce znajdują się osobne budynki typu studio — dla gości lub pod wynajem.\n\nOgród jest duży i zadbany i to on nadaje nieruchomości charakter: wygoda miasta i własny zielony zakątek blisko morza.',
    },
    address: {
      en: 'Quiet green area, Durres',
      ru: 'Тихий зелёный район, Дуррес',
      uk: 'Тихий зелений район, Дуррес',
      sq: 'Zonë e qetë dhe e gjelbër, Durrës',
      it: 'Zona verde e tranquilla, Durazzo',
      pl: 'Cicha, zielona okolica, Durres',
    },
    offers: [
      {
        iconKey: 'home',
        title: {
          en: '400 m² house on a 1,000 m² plot',
          ru: 'Дом 400 м² на участке 10 соток',
          uk: 'Будинок 400 м² на ділянці 10 соток',
          sq: 'Shtëpi 400 m² në truall 1.000 m²',
          it: 'Casa di 400 m² su terreno di 1.000 m²',
          pl: 'Dom 400 m² na działce 1000 m²',
        },
      },
      {
        iconKey: 'tree',
        title: {
          en: 'Large, well-kept garden',
          ru: 'Большой ухоженный сад',
          uk: 'Великий доглянутий сад',
          sq: 'Kopsht i madh dhe i mirëmbajtur',
          it: 'Giardino ampio e curato',
          pl: 'Duży, zadbany ogród',
        },
      },
      {
        iconKey: 'key',
        title: {
          en: 'Separate guest studios on the plot',
          ru: 'Отдельные студии для гостей на участке',
          uk: 'Окремі студії для гостей на ділянці',
          sq: 'Studio të veçanta për mysafirë në truall',
          it: 'Monolocali indipendenti per gli ospiti',
          pl: 'Osobne studia dla gości na działce',
        },
      },
      {
        iconKey: 'layout',
        title: {
          en: 'Two living floors, four bathrooms',
          ru: 'Два жилых этажа, четыре санузла',
          uk: 'Два житлові поверхи, чотири санвузли',
          sq: 'Dy kate banimi, katër tualete',
          it: 'Due piani abitativi, quattro bagni',
          pl: 'Dwie kondygnacje mieszkalne, cztery łazienki',
        },
      },
    ],
  },

  {
    datoId: 'QWQRfuwYSOO3gV158HEg8g',
    slug: 'prodaetsya-otel-u-morya-deystvuyushchiy-biznes-zemlya',
    city: 'durres',
    district: 'plazh',
    type: 'commercial-space',
    status: 'sale',
    price: 2000000,
    area: 800,
    bedrooms: 18,
    bathrooms: 18,
    title: {
      en: 'Operating Seafront Hotel, 800 m² plus 500 m² of Land — Durres',
      ru: 'Действующий отель у моря, 800 м² и 500 м² земли — Дуррес',
      uk: 'Діючий готель біля моря, 800 м² і 500 м² землі — Дуррес',
      sq: 'Hotel në punë pranë detit, 800 m² plus 500 m² truall — Durrës',
      it: 'Hotel avviato fronte mare, 800 m² più 500 m² di terreno — Durazzo',
      pl: 'Działający hotel przy morzu, 800 m² plus 500 m² gruntu — Durres',
    },
    shortDescription: {
      en: 'A working four-storey hotel a hundred metres from the sea in Plazh: 18 equipped rooms, commercial ground floor and 500 m² of adjoining land.',
      ru: 'Действующий четырёхэтажный отель в ста метрах от моря в районе Пляж: 18 оборудованных номеров, коммерческий первый этаж и 500 м² земли рядом.',
      uk: 'Діючий чотириповерховий готель за сто метрів від моря в районі Пляж: 18 обладнаних номерів, комерційний перший поверх і 500 м² землі поряд.',
      sq: 'Hotel katërkatësh në punë njëqind metra nga deti në Plazh: 18 dhoma të pajisura, kati përdhes komercial dhe 500 m² truall ngjitur.',
      it: 'Hotel avviato di quattro piani a cento metri dal mare a Plazh: 18 camere attrezzate, piano terra commerciale e 500 m² di terreno adiacente.',
      pl: 'Działający czteropiętrowy hotel sto metrów od morza w Plazh: 18 wyposażonych pokoi, komercyjny parter i 500 m² przyległego gruntu.',
    },
    description: {
      en: 'An operating hotel in the tourist part of Durres, a hundred metres from the sea. Four floors, 800 m² of built area, plus 500 m² of land alongside where a pool could be built.\n\nThe ground floor is commercial: a café, a dining room and premises for additional business. Floors two to four hold eighteen fully equipped rooms, six per floor, with modern furniture, air conditioning, good appliances and renewed plumbing.\n\nThe beach, shops, bars, restaurants, the promenade, a school, a bank and a post office are all within walking distance.\n\nThe business is already running, with the seasonal tourist flow that comes with this stretch of coast. The owner is open to a serious negotiation.',
      ru: 'Действующий отель в туристической части Дурреса, в ста метрах от моря. Четыре этажа, 800 м² застройки плюс 500 м² земли рядом, где можно построить бассейн.\n\nПервый этаж коммерческий: кафе, столовая и помещения под дополнительный бизнес. На втором-четвёртом этажах — восемнадцать полностью оборудованных номеров, по шесть на этаже, с современной мебелью, кондиционерами, хорошей бытовой техникой и обновлённой сантехникой.\n\nПляж, магазины, бары, рестораны, набережная, школа, банк и почта — в пешей доступности.\n\nБизнес уже работает, с сезонным потоком туристов, характерным для этого участка побережья. Собственник готов к серьёзному обсуждению цены.',
      uk: 'Діючий готель у туристичній частині Дурреса, за сто метрів від моря. Чотири поверхи, 800 м² забудови плюс 500 м² землі поряд, де можна побудувати басейн.\n\nПерший поверх комерційний: кафе, їдальня та приміщення під додатковий бізнес. На другому-четвертому поверхах — вісімнадцять повністю обладнаних номерів, по шість на поверсі, із сучасними меблями, кондиціонерами, хорошою побутовою технікою та оновленою сантехнікою.\n\nПляж, магазини, бари, ресторани, набережна, школа, банк і пошта — у пішій доступності.\n\nБізнес уже працює, із сезонним потоком туристів, характерним для цієї ділянки узбережжя. Власник готовий до серйозного обговорення ціни.',
      sq: 'Hotel në punë në pjesën turistike të Durrësit, njëqind metra nga deti. Katër kate, 800 m² sipërfaqe e ndërtuar, plus 500 m² truall ngjitur ku mund të ndërtohet një pishinë.\n\nKati përdhes është komercial: kafene, mensë dhe ambiente për biznes shtesë. Katet dy deri katër kanë tetëmbëdhjetë dhoma plotësisht të pajisura, gjashtë për kat, me mobilie moderne, kondicionerë, pajisje të mira dhe hidrosanitare të rinovuara.\n\nPlazhi, dyqanet, baret, restorantet, shëtitorja, shkolla, banka dhe posta janë të gjitha në këmbë.\n\nBiznesi është tashmë në funksionim, me fluksin sezonal të turistëve që karakterizon këtë pjesë të bregdetit. Pronari është i hapur për një negociatë serioze.',
      it: 'Hotel in attività nella zona turistica di Durazzo, a cento metri dal mare. Quattro piani, 800 m² di superficie costruita, più 500 m² di terreno adiacente dove si potrebbe realizzare una piscina.\n\nIl piano terra è commerciale: un bar, una sala da pranzo e locali per attività aggiuntive. Dal secondo al quarto piano ci sono diciotto camere completamente attrezzate, sei per piano, con mobili moderni, aria condizionata, buoni elettrodomestici e impianti idraulici rinnovati.\n\nSpiaggia, negozi, bar, ristoranti, lungomare, scuola, banca e ufficio postale sono tutti a piedi.\n\nL’attività è già avviata, con il flusso turistico stagionale tipico di questo tratto di costa. Il proprietario è disponibile a una trattativa seria.',
      pl: 'Działający hotel w turystycznej części Durres, sto metrów od morza. Cztery piętra, 800 m² powierzchni zabudowy plus 500 m² przyległego gruntu, gdzie można zbudować basen.\n\nParter jest komercyjny: kawiarnia, jadalnia i lokale pod dodatkową działalność. Na piętrach od drugiego do czwartego znajduje się osiemnaście w pełni wyposażonych pokoi, po sześć na piętrze, z nowoczesnymi meblami, klimatyzacją, dobrym sprzętem i odnowioną instalacją sanitarną.\n\nPlaża, sklepy, bary, restauracje, promenada, szkoła, bank i poczta są w zasięgu spaceru.\n\nBiznes już działa, z sezonowym ruchem turystycznym charakterystycznym dla tego odcinka wybrzeża. Właściciel jest otwarty na poważne negocjacje.',
    },
    address: {
      en: 'Plazh (Durres Beach), Durres — 100 m from the sea',
      ru: 'Район Пляж, Дуррес — 100 м до моря',
      uk: 'Район Пляж, Дуррес — 100 м до моря',
      sq: 'Plazh, Durrës — 100 m nga deti',
      it: 'Plazh, Durazzo — 100 m dal mare',
      pl: 'Plazh, Durres — 100 m od morza',
    },
    offers: [
      {
        iconKey: 'zap',
        title: {
          en: 'Operating business, not a shell',
          ru: 'Действующий бизнес, а не пустое здание',
          uk: 'Діючий бізнес, а не порожня будівля',
          sq: 'Biznes në funksionim, jo thjesht një ndërtesë',
          it: 'Attività avviata, non un immobile vuoto',
          pl: 'Działający biznes, nie pusty budynek',
        },
      },
      {
        iconKey: 'home',
        title: {
          en: '18 equipped rooms across three floors',
          ru: '18 оборудованных номеров на трёх этажах',
          uk: '18 обладнаних номерів на трьох поверхах',
          sq: '18 dhoma të pajisura në tre kate',
          it: '18 camere attrezzate su tre piani',
          pl: '18 wyposażonych pokoi na trzech piętrach',
        },
      },
      {
        iconKey: 'building',
        title: {
          en: 'Commercial ground floor: café and dining room',
          ru: 'Коммерческий первый этаж: кафе и столовая',
          uk: 'Комерційний перший поверх: кафе та їдальня',
          sq: 'Kati përdhes komercial: kafene dhe mensë',
          it: 'Piano terra commerciale: bar e sala da pranzo',
          pl: 'Komercyjny parter: kawiarnia i jadalnia',
        },
      },
      {
        iconKey: 'tree',
        title: {
          en: '500 m² of land, room for a pool',
          ru: '500 м² земли, есть место под бассейн',
          uk: '500 м² землі, є місце під басейн',
          sq: '500 m² truall, hapësirë për pishinë',
          it: '500 m² di terreno, spazio per una piscina',
          pl: '500 m² gruntu, miejsce na basen',
        },
      },
      {
        iconKey: 'waves',
        title: {
          en: '100 m from the sea, in the tourist zone',
          ru: '100 м до моря, в туристической зоне',
          uk: '100 м до моря, у туристичній зоні',
          sq: '100 m nga deti, në zonën turistike',
          it: '100 m dal mare, in zona turistica',
          pl: '100 m od morza, w strefie turystycznej',
        },
      },
    ],
    review:
      'Mapped to commercial-space; bedrooms/bathrooms hold the room count (18), which is how the source describes it. Consider whether a dedicated hotel type is worth adding.',
  },

  {
    datoId: 'ejcIpg6JRhybIqtO9KE9jA',
    slug: 'prodazha-uyutnoy-kvartiry-1-1-u-gory',
    city: 'vlore',
    type: 'apartment',
    status: 'sale',
    price: 87000,
    area: 49,
    bedrooms: 1,
    bathrooms: 1,
    title: {
      en: 'One-Bedroom Apartment between the Mountain and the Sea — Vlore',
      ru: 'Квартира 1+1 между горой и морем — Влёра',
      uk: 'Квартира 1+1 між горою та морем — Влера',
      sq: 'Apartament 1+1 mes malit dhe detit — Vlorë',
      it: 'Appartamento 1+1 tra la montagna e il mare — Valona',
      pl: 'Mieszkanie 1+1 między górą a morzem — Wlora',
    },
    shortDescription: {
      en: 'A 49 m² one-bedroom apartment in Vlore at the foot of the mountain, three hundred metres from the sea. Ground floor, sold directly by the owner.',
      ru: 'Квартира 1+1 площадью 49 м² во Влёре у подножия горы, в трёхстах метрах от моря. Первый этаж, прямая продажа от собственника.',
      uk: 'Квартира 1+1 площею 49 м² у Влері біля підніжжя гори, за триста метрів від моря. Перший поверх, прямий продаж від власника.',
      sq: 'Apartament 1+1 me sipërfaqe 49 m² në Vlorë në rrëzë të malit, treqind metra nga deti. Kati përdhes, shitje direkt nga pronari.',
      it: 'Appartamento 1+1 di 49 m² a Valona ai piedi della montagna, a trecento metri dal mare. Piano terra, vendita diretta dal proprietario.',
      pl: 'Mieszkanie 1+1 o powierzchni 49 m² we Wlorze u podnóża góry, trzysta metrów od morza. Parter, sprzedaż bezpośrednio od właściciela.',
    },
    description: {
      en: 'A one-bedroom apartment of 49 m² in Vlore, at the foot of the mountain and three hundred metres from the sea. Five minutes on foot one way brings you to the beach; five minutes the other way, to the quiet of the hills.\n\nThe flat is on the ground floor and dry.\n\nIt is sold directly by the owner, who is open to discussing terms.',
      ru: 'Квартира 1+1 площадью 49 м² во Влёре, у подножия горы и в трёхстах метрах от моря. Пять минут пешком в одну сторону — и вы на пляже, пять минут в другую — и вокруг тишина гор.\n\nКвартира на первом этаже, сухая.\n\nПрямая продажа от собственника, условия готов обсуждать.',
      uk: 'Квартира 1+1 площею 49 м² у Влері, біля підніжжя гори й за триста метрів від моря. Пʼять хвилин пішки в один бік — і ви на пляжі, пʼять хвилин в інший — і навколо тиша гір.\n\nКвартира на першому поверсі, суха.\n\nПрямий продаж від власника, умови готовий обговорювати.',
      sq: 'Apartament 1+1 me sipërfaqe 49 m² në Vlorë, në rrëzë të malit dhe treqind metra nga deti. Pesë minuta në këmbë nga njëra anë ju çojnë në plazh; pesë minuta nga ana tjetër, në qetësinë e kodrave.\n\nApartamenti ndodhet në katin përdhes dhe është i thatë.\n\nShitet direkt nga pronari, i cili është i gatshëm të diskutojë kushtet.',
      it: 'Appartamento 1+1 di 49 m² a Valona, ai piedi della montagna e a trecento metri dal mare. Cinque minuti a piedi da un lato portano alla spiaggia; cinque minuti dall’altro, alla quiete delle colline.\n\nL’appartamento è al piano terra ed è asciutto.\n\nVendita diretta dal proprietario, disponibile a discutere le condizioni.',
      pl: 'Mieszkanie 1+1 o powierzchni 49 m² we Wlorze, u podnóża góry i trzysta metrów od morza. Pięć minut pieszo w jedną stronę prowadzi na plażę, pięć minut w drugą — w ciszę wzgórz.\n\nMieszkanie znajduje się na parterze i jest suche.\n\nSprzedaż bezpośrednio od właściciela, który jest otwarty na rozmowę o warunkach.',
    },
    address: {
      en: 'Vlore, at the foot of the mountain, 300 m from the sea',
      ru: 'Влёра, у подножия горы, 300 м до моря',
      uk: 'Влера, біля підніжжя гори, 300 м до моря',
      sq: 'Vlorë, në rrëzë të malit, 300 m nga deti',
      it: 'Valona, ai piedi della montagna, 300 m dal mare',
      pl: 'Wlora, u podnóża góry, 300 m od morza',
    },
    offers: [
      {
        iconKey: 'waves',
        title: {
          en: '300 m from the sea, 5 minutes on foot',
          ru: '300 м до моря, 5 минут пешком',
          uk: '300 м до моря, 5 хвилин пішки',
          sq: '300 m nga deti, 5 minuta në këmbë',
          it: '300 m dal mare, 5 minuti a piedi',
          pl: '300 m od morza, 5 minut pieszo',
        },
      },
      {
        iconKey: 'tree',
        title: {
          en: 'At the foot of the mountain, quiet on that side',
          ru: 'У подножия горы, с этой стороны тихо',
          uk: 'Біля підніжжя гори, з цього боку тихо',
          sq: 'Në rrëzë të malit, nga ajo anë është qetësi',
          it: 'Ai piedi della montagna, tranquillo su quel lato',
          pl: 'U podnóża góry, po tej stronie cicho',
        },
      },
      {
        iconKey: 'key',
        title: {
          en: 'Sold directly by the owner',
          ru: 'Прямая продажа от собственника',
          uk: 'Прямий продаж від власника',
          sq: 'Shitet direkt nga pronari',
          it: 'Vendita diretta dal proprietario',
          pl: 'Sprzedaż bezpośrednio od właściciela',
        },
      },
    ],
    review: 'Dato lists bedrooms=2 while the title and text say 1+1; kept as one bedroom.',
  },
]
