import type {PropertyContent} from './types'

/** Objects 11–16: Mali i Robit 46 m², Plepa 1+1, Plazh 1+1 42 m², two Shëngjin flats, Tocak studio. */
export const BATCH_3: PropertyContent[] = [
  {
    datoId: 'I1KpRhu0S1OSf3WN7Q27wg',
    slug: 'prodazha-mali-i-robit-new-residence-11-or-46-m',
    city: 'durres',
    district: 'mali-i-robit',
    type: 'apartment',
    status: 'sale',
    price: 83000,
    area: 46,
    bedrooms: 1,
    bathrooms: 1,
    title: {
      en: 'New-Build One-Bedroom Apartment 46 m² — Mali i Robit, Durres',
      ru: 'Квартира 1+1, 46 м², в новостройке — Мали и Робит, Дуррес',
      uk: 'Квартира 1+1, 46 м², у новобудові — Малі і Робіт, Дуррес',
      sq: 'Apartament 1+1, 46 m², në ndërtim të ri — Mali i Robit, Durrës',
      it: 'Appartamento 1+1 di 46 m² in nuova costruzione — Mali i Robit, Durazzo',
      pl: 'Mieszkanie 1+1, 46 m², w nowym budynku — Mali i Robit, Durres',
    },
    shortDescription: {
      en: 'A 46 m² apartment in a 2026 building in Mali i Robit, 250 metres from the sea, furnished, with Multi Split heating and cooling in every room.',
      ru: 'Квартира 46 м² в доме 2026 года в Мали и Робит, в 250 метрах от моря, с мебелью и системой Multi Split в каждой комнате.',
      uk: 'Квартира 46 м² у будинку 2026 року в Малі і Робіт, за 250 метрів від моря, з меблями та системою Multi Split у кожній кімнаті.',
      sq: 'Apartament 46 m² në një pallat të vitit 2026 në Mali i Robit, 250 metra nga deti, i mobiluar, me Multi Split në çdo dhomë.',
      it: 'Appartamento di 46 m² in un edificio del 2026 a Mali i Robit, a 250 metri dal mare, arredato, con Multi Split in ogni stanza.',
      pl: 'Mieszkanie 46 m² w budynku z 2026 roku w Mali i Robit, 250 metrów od morza, umeblowane, z Multi Split w każdym pomieszczeniu.',
    },
    description: {
      en: 'A one-bedroom apartment of 46 m² in a new 2026 building in Mali i Robit, 250 metres from the sea. Third floor, with a lift rated for eight people.\n\nThe layout is a spacious living room with a kitchen, a separate bedroom and a modern bathroom.\n\nIt is sold furnished, with contemporary furniture and appliances, a Multi Split system heating and cooling each room, modern lighting and good-quality finishes. A parking space can be bought separately.\n\nThis is the larger of two flats offered in the same building; the other is 42 m².',
      ru: 'Квартира 1+1 площадью 46 м² в новом доме 2026 года в Мали и Робит, в 250 метрах от моря. Третий этаж, лифт на восемь человек.\n\nПланировка: просторная гостиная с кухней, отдельная спальня и современный санузел.\n\nПродаётся с мебелью — современная обстановка и техника, система Multi Split с отоплением и охлаждением в каждой комнате, современное освещение и качественная отделка. Парковочное место можно приобрести отдельно.\n\nЭто большая из двух квартир, предлагаемых в этом доме; вторая — 42 м².',
      uk: 'Квартира 1+1 площею 46 м² у новому будинку 2026 року в Малі і Робіт, за 250 метрів від моря. Третій поверх, ліфт на вісім осіб.\n\nПланування: простора вітальня з кухнею, окрема спальня та сучасний санвузол.\n\nПродається з меблями — сучасна обстановка й техніка, система Multi Split з опаленням і охолодженням у кожній кімнаті, сучасне освітлення та якісне оздоблення. Паркувальне місце можна придбати окремо.\n\nЦе більша з двох квартир, що пропонуються в цьому будинку; друга — 42 м².',
      sq: 'Apartament 1+1 me sipërfaqe 46 m² në një pallat të ri të vitit 2026 në Mali i Robit, 250 metra nga deti. Kati i tretë, me ashensor për tetë veta.\n\nPlanimetria: ndenjë e gjerë me kuzhinë, dhomë gjumi më vete dhe tualet modern.\n\nShitet i mobiluar — mobilie e pajisje moderne, sistem Multi Split me ngrohje dhe ftohje në çdo dhomë, ndriçim modern dhe materiale cilësore. Vendi i parkimit blihet veçmas.\n\nKy është më i madhi nga dy apartamentet që ofrohen në të njëjtin pallat; tjetri është 42 m².',
      it: 'Appartamento 1+1 di 46 m² in un nuovo edificio del 2026 a Mali i Robit, a 250 metri dal mare. Terzo piano, con ascensore per otto persone.\n\nLa distribuzione: ampio soggiorno con cucina, camera separata e bagno moderno.\n\nViene venduto arredato, con mobili ed elettrodomestici contemporanei, un sistema Multi Split che riscalda e raffresca ogni stanza, illuminazione moderna e finiture di buona qualità. Il posto auto è acquistabile separatamente.\n\nÈ il più grande dei due appartamenti proposti nello stesso edificio; l’altro è di 42 m².',
      pl: 'Mieszkanie 1+1 o powierzchni 46 m² w nowym budynku z 2026 roku w Mali i Robit, 250 metrów od morza. Trzecie piętro, winda na osiem osób.\n\nUkład: przestronny salon z kuchnią, osobna sypialnia i nowoczesna łazienka.\n\nSprzedawane z meblami — współczesne wyposażenie i sprzęt, system Multi Split z ogrzewaniem i chłodzeniem w każdym pomieszczeniu, nowoczesne oświetlenie i dobre wykończenie. Miejsce parkingowe do kupienia osobno.\n\nTo większe z dwóch mieszkań oferowanych w tym samym budynku; drugie ma 42 m².',
    },
    address: {
      en: 'Mali i Robit, Durres',
      ru: 'Мали и Робит, Дуррес',
      uk: 'Малі і Робіт, Дуррес',
      sq: 'Mali i Robit, Durrës',
      it: 'Mali i Robit, Durazzo',
      pl: 'Mali i Robit, Durres',
    },
    offers: [
      {
        iconKey: 'building',
        title: {
          en: 'New 2026 building',
          ru: 'Новый дом 2026 года',
          uk: 'Новий будинок 2026 року',
          sq: 'Pallat i ri i vitit 2026',
          it: 'Edificio nuovo del 2026',
          pl: 'Nowy budynek z 2026 roku',
        },
      },
      {
        iconKey: 'snowflake',
        title: {
          en: 'Multi Split heating and cooling in every room',
          ru: 'Multi Split: отопление и охлаждение в каждой комнате',
          uk: 'Multi Split: опалення й охолодження в кожній кімнаті',
          sq: 'Multi Split: ngrohje dhe ftohje në çdo dhomë',
          it: 'Multi Split: riscaldamento e raffrescamento in ogni stanza',
          pl: 'Multi Split: ogrzewanie i chłodzenie w każdym pomieszczeniu',
        },
      },
      {
        iconKey: 'waves',
        title: {
          en: '250 m from the sea',
          ru: '250 м до моря',
          uk: '250 м до моря',
          sq: '250 m nga deti',
          it: '250 m dal mare',
          pl: '250 m od morza',
        },
      },
      {
        iconKey: 'sofa',
        title: {
          en: 'Fully furnished with modern appliances',
          ru: 'Полностью меблирована, современная техника',
          uk: 'Повністю вмебльована, сучасна техніка',
          sq: 'Plotësisht e mobiluar, pajisje moderne',
          it: 'Completamente arredato, elettrodomestici moderni',
          pl: 'W pełni umeblowane, nowoczesny sprzęt',
        },
      },
      {
        iconKey: 'parking',
        title: {
          en: 'Parking space available to buy',
          ru: 'Парковочное место можно купить',
          uk: 'Паркомісце можна купити',
          sq: 'Vend parkimi i blershëm',
          it: 'Posto auto acquistabile',
          pl: 'Miejsce parkingowe do kupienia',
        },
      },
    ],
  },

  {
    datoId: 'GwqdStmTScajmGbeni7UAg',
    slug: 'prodaetsya-bolshaya-kvartira-1-1-v-rayone-plepa',
    city: 'durres',
    district: 'plepa-durres',
    type: 'apartment',
    status: 'sale',
    price: 98000,
    area: 68,
    bedrooms: 1,
    bathrooms: 1,
    title: {
      en: 'Spacious One-Bedroom Apartment 68 m² — Plepa, Durres',
      ru: 'Просторная квартира 1+1, 68 м² — Плепа, Дуррес',
      uk: 'Простора квартира 1+1, 68 м² — Плепа, Дуррес',
      sq: 'Apartament i gjerë 1+1, 68 m² — Plepa, Durrës',
      it: 'Ampio appartamento 1+1 di 68 m² — Plepa, Durazzo',
      pl: 'Przestronne mieszkanie 1+1, 68 m² — Plepa, Durres',
    },
    shortDescription: {
      en: 'A 68.4 m² one-bedroom apartment on the ninth floor in Plepa, a hundred metres from the sea, with new furniture and appliances.',
      ru: 'Квартира 1+1 площадью 68,4 м² на девятом этаже в Плепе, в ста метрах от моря, с новой мебелью и техникой.',
      uk: 'Квартира 1+1 площею 68,4 м² на девʼятому поверсі в Плепі, за сто метрів від моря, з новими меблями й технікою.',
      sq: 'Apartament 1+1 me sipërfaqe 68,4 m² në katin e nëntë në Plepa, njëqind metra nga deti, me mobilie dhe pajisje të reja.',
      it: 'Appartamento 1+1 di 68,4 m² al nono piano a Plepa, a cento metri dal mare, con mobili ed elettrodomestici nuovi.',
      pl: 'Mieszkanie 1+1 o powierzchni 68,4 m² na dziewiątym piętrze w Plepa, sto metrów od morza, z nowymi meblami i sprzętem.',
    },
    description: {
      en: 'A one-bedroom apartment of 68.4 m² in Plepa, Durres, a hundred metres from the sea. Ninth floor, in a building with a lift.\n\nThe furniture and appliances are new, and the building is solid and comfortable to live in.\n\nPlepa is used by tourists and residents alike, which keeps demand steady outside the summer months as well.',
      ru: 'Квартира 1+1 площадью 68,4 м² в районе Плепа, Дуррес, в ста метрах от моря. Девятый этаж, дом с лифтом.\n\nМебель и техника новые, дом прочный и удобный для проживания.\n\nПлепа востребована и у туристов, и у местных жителей, поэтому спрос здесь держится и вне летних месяцев.',
      uk: 'Квартира 1+1 площею 68,4 м² у районі Плепа, Дуррес, за сто метрів від моря. Девʼятий поверх, будинок із ліфтом.\n\nМеблі й техніка нові, будинок міцний і зручний для проживання.\n\nПлепа затребувана і в туристів, і в місцевих мешканців, тож попит тут тримається й поза літніми місяцями.',
      sq: 'Apartament 1+1 me sipërfaqe 68,4 m² në Plepa, Durrës, njëqind metra nga deti. Kati i nëntë, në pallat me ashensor.\n\nMobiliet dhe pajisjet janë të reja, ndërsa pallati është i qëndrueshëm dhe i rehatshëm për banim.\n\nPlepa përdoret njësoj nga turistët dhe banorët vendas, prandaj kërkesa mbetet e qëndrueshme edhe jashtë muajve të verës.',
      it: 'Appartamento 1+1 di 68,4 m² a Plepa, Durazzo, a cento metri dal mare. Nono piano, in un edificio con ascensore.\n\nMobili ed elettrodomestici sono nuovi e l’edificio è solido e confortevole da abitare.\n\nPlepa è frequentata sia dai turisti sia dai residenti, il che mantiene stabile la domanda anche fuori dai mesi estivi.',
      pl: 'Mieszkanie 1+1 o powierzchni 68,4 m² w Plepa, Durres, sto metrów od morza. Dziewiąte piętro, budynek z windą.\n\nMeble i sprzęt są nowe, a budynek solidny i wygodny do mieszkania.\n\nPlepa jest wykorzystywana zarówno przez turystów, jak i mieszkańców, co utrzymuje popyt także poza miesiącami letnimi.',
    },
    address: {
      en: 'Plepa, Durres',
      ru: 'Плепа, Дуррес',
      uk: 'Плепа, Дуррес',
      sq: 'Plepa, Durrës',
      it: 'Plepa, Durazzo',
      pl: 'Plepa, Durres',
    },
    offers: [
      {
        iconKey: 'waves',
        title: {
          en: '100 m from the sea',
          ru: '100 м до моря',
          uk: '100 м до моря',
          sq: '100 m nga deti',
          it: '100 m dal mare',
          pl: '100 m od morza',
        },
      },
      {
        iconKey: 'sofa',
        title: {
          en: 'New furniture and appliances',
          ru: 'Новая мебель и техника',
          uk: 'Нові меблі й техніка',
          sq: 'Mobilie dhe pajisje të reja',
          it: 'Mobili ed elettrodomestici nuovi',
          pl: 'Nowe meble i sprzęt',
        },
      },
      {
        iconKey: 'elevator',
        title: {
          en: 'Ninth floor, building with a lift',
          ru: 'Девятый этаж, дом с лифтом',
          uk: 'Девʼятий поверх, будинок із ліфтом',
          sq: 'Kati i nëntë, pallat me ashensor',
          it: 'Nono piano, edificio con ascensore',
          pl: 'Dziewiąte piętro, budynek z windą',
        },
      },
    ],
    review:
      'Source claims the flat qualifies three people for a residence permit. Dropped from the copy — legal claim about the buyer, not the property. Dato lists bedrooms=2 while the title and text say 1+1; kept as one bedroom.',
  },

  {
    datoId: 'TLrGJuVuRwuJ4CrVWPzAfw',
    slug: 'prodazha-kvartiry-11-u-morya-or-70-m-do-plyazha',
    city: 'durres',
    district: 'plazh',
    type: 'apartment',
    status: 'sale',
    price: 78000,
    area: 42,
    bedrooms: 1,
    bathrooms: 1,
    title: {
      en: 'One-Bedroom Apartment 70 m from the Beach — Plazh, Durres',
      ru: 'Квартира 1+1 в 70 м от пляжа — Пляж, Дуррес',
      uk: 'Квартира 1+1 за 70 м від пляжу — Пляж, Дуррес',
      sq: 'Apartament 1+1, 70 m nga plazhi — Plazh, Durrës',
      it: 'Appartamento 1+1 a 70 m dalla spiaggia — Plazh, Durazzo',
      pl: 'Mieszkanie 1+1, 70 m od plaży — Plazh, Durres',
    },
    shortDescription: {
      en: 'A 42 m² flat converted from a studio into a proper one-bedroom layout, seventy metres from the sea on the ninth floor.',
      ru: 'Квартира 42 м², переделанная из студии в полноценный формат 1+1, в семидесяти метрах от моря, девятый этаж.',
      uk: 'Квартира 42 м², перероблена зі студії на повноцінний формат 1+1, за сімдесят метрів від моря, девʼятий поверх.',
      sq: 'Apartament 42 m², i kthyer nga studio në një 1+1 të plotë, shtatëdhjetë metra nga deti, kati i nëntë.',
      it: 'Appartamento di 42 m², trasformato da monolocale in un vero 1+1, a settanta metri dal mare, nono piano.',
      pl: 'Mieszkanie 42 m², przerobione z kawalerki na pełne 1+1, siedemdziesiąt metrów od morza, dziewiąte piętro.',
    },
    description: {
      en: 'A 42 m² apartment in Plazh, Durres, seventy metres from the sea. It began as a studio and was converted into a proper one-bedroom layout: a separate bedroom, a living room with a kitchen and its own hallway, which is what makes the small footprint work.\n\nNinth floor, not the top one.\n\nThe district keeps shops, cafés, supermarkets, transport and the promenade running all year, so the flat suits permanent living as much as holidays or letting. The owner will consider a serious offer on site.',
      ru: 'Квартира 42 м² в районе Пляж, Дуррес, в семидесяти метрах от моря. Изначально это была студия, её переделали в полноценный формат 1+1: отдельная спальня, гостиная с кухней и собственный коридор — именно это и делает небольшую площадь рабочей.\n\nДевятый этаж, не последний.\n\nВ районе круглый год работают магазины, кафе, супермаркеты, транспорт и набережная, поэтому квартира подходит и для постоянной жизни, и для отдыха, и под аренду. Собственник готов обсудить серьёзное предложение на месте.',
      uk: 'Квартира 42 м² у районі Пляж, Дуррес, за сімдесят метрів від моря. Спочатку це була студія, її переробили на повноцінний формат 1+1: окрема спальня, вітальня з кухнею та власний коридор — саме це й робить невелику площу робочою.\n\nДевʼятий поверх, не останній.\n\nУ районі цілий рік працюють магазини, кафе, супермаркети, транспорт і набережна, тож квартира підходить і для постійного життя, і для відпочинку, і під оренду. Власник готовий обговорити серйозну пропозицію на місці.',
      sq: 'Apartament 42 m² në Plazh, Durrës, shtatëdhjetë metra nga deti. Fillimisht ka qenë studio dhe është kthyer në një 1+1 të plotë: dhomë gjumi më vete, ndenjë me kuzhinë dhe korridor të vetin — pikërisht kjo e bën sipërfaqen e vogël funksionale.\n\nKati i nëntë, jo i fundit.\n\nZona i mban dyqanet, kafenetë, supermarketet, transportin dhe shëtitoren aktive gjatë gjithë vitit, prandaj apartamenti i shërben si banimit të përhershëm, ashtu edhe pushimeve a qirasë. Pronari pranon të diskutojë një ofertë serioze në vend.',
      it: 'Appartamento di 42 m² a Plazh, Durazzo, a settanta metri dal mare. Nato come monolocale, è stato trasformato in un vero 1+1: camera separata, soggiorno con cucina e un proprio corridoio, ed è questo a rendere funzionale la metratura contenuta.\n\nNono piano, non l’ultimo.\n\nIl quartiere mantiene negozi, bar, supermercati, trasporti e lungomare attivi tutto l’anno, quindi l’appartamento si presta sia alla residenza stabile sia alle vacanze o all’affitto. Il proprietario valuta un’offerta seria in loco.',
      pl: 'Mieszkanie 42 m² w Plazh, Durres, siedemdziesiąt metrów od morza. Powstało z kawalerki, którą przerobiono na pełne 1+1: osobna sypialnia, salon z kuchnią i własny przedpokój — to właśnie sprawia, że niewielki metraż działa.\n\nDziewiąte piętro, nie ostatnie.\n\nDzielnica utrzymuje sklepy, kawiarnie, supermarkety, transport i promenadę czynne przez cały rok, więc mieszkanie nadaje się zarówno do stałego życia, jak i na wakacje czy pod wynajem. Właściciel rozważy poważną ofertę na miejscu.',
    },
    address: {
      en: 'Plazh (Durres Beach), Durres',
      ru: 'Район Пляж, Дуррес',
      uk: 'Район Пляж, Дуррес',
      sq: 'Plazh, Durrës',
      it: 'Plazh, Durazzo',
      pl: 'Plazh, Durres',
    },
    offers: [
      {
        iconKey: 'waves',
        title: {
          en: '70 m from the beach',
          ru: '70 м до пляжа',
          uk: '70 м до пляжу',
          sq: '70 m nga plazhi',
          it: '70 m dalla spiaggia',
          pl: '70 m od plaży',
        },
      },
      {
        iconKey: 'layout',
        title: {
          en: 'Converted to a separate-bedroom layout',
          ru: 'Переделана в формат с отдельной спальней',
          uk: 'Перероблена у формат з окремою спальнею',
          sq: 'E kthyer në format me dhomë gjumi më vete',
          it: 'Convertito in una pianta con camera separata',
          pl: 'Przerobione na układ z osobną sypialnią',
        },
      },
      {
        iconKey: 'building',
        title: {
          en: 'Year-round infrastructure in the district',
          ru: 'Круглогодичная инфраструктура в районе',
          uk: 'Цілорічна інфраструктура в районі',
          sq: 'Infrastrukturë gjatë gjithë vitit në zonë',
          it: 'Servizi attivi tutto l’anno nel quartiere',
          pl: 'Całoroczna infrastruktura w dzielnicy',
        },
      },
    ],
    review:
      'Source claims the certificate area qualifies two people for a residence permit. Dropped from the copy.',
  },

  {
    datoId: 'EutOAd84TCaX9MgVDzVpVQ',
    slug: 'prodazha-vidovoy-kvartiry-2-1-shendzhin',
    city: 'shengjin',
    district: 'center-shengjin',
    type: 'apartment',
    status: 'sale',
    price: 160000,
    area: 90,
    bedrooms: 2,
    bathrooms: 1,
    title: {
      en: 'Front-Line Two-Bedroom Apartment with Direct Sea View — Shengjin',
      ru: 'Квартира 2+1 на первой линии с прямым видом на море — Шенджин',
      uk: 'Квартира 2+1 на першій лінії з прямим видом на море — Шенджин',
      sq: 'Apartament 2+1 në vijë të parë me pamje të drejtpërdrejtë nga deti — Shëngjin',
      it: 'Appartamento 2+1 in prima linea con vista mare diretta — Shengjin',
      pl: 'Mieszkanie 2+1 w pierwszej linii z bezpośrednim widokiem na morze — Shengjin',
    },
    shortDescription: {
      en: 'A 90 m² two-bedroom apartment in a front-line building in Shengjin, with the sea directly in front of the windows and two balconies.',
      ru: 'Квартира 2+1 площадью 90 м² в доме на первой линии в Шенджине: море прямо перед окнами, два балкона.',
      uk: 'Квартира 2+1 площею 90 м² у будинку на першій лінії в Шенджині: море просто перед вікнами, два балкони.',
      sq: 'Apartament 2+1 me sipërfaqe 90 m² në një pallat në vijë të parë në Shëngjin: deti pikërisht para dritareve, dy ballkone.',
      it: 'Appartamento 2+1 di 90 m² in un edificio in prima linea a Shengjin: il mare proprio davanti alle finestre e due balconi.',
      pl: 'Mieszkanie 2+1 o powierzchni 90 m² w budynku w pierwszej linii w Shengjin: morze wprost przed oknami i dwa balkony.',
    },
    description: {
      en: 'A two-bedroom apartment in Shengjin, on the northern Albanian coast, in a building standing on the front line. The sea is directly in front of the windows, with a straight view from the living room.\n\nThe total area is 90 m², of which 85 m² are on the certificate. The layout gives two separate bedrooms, a large living room and two balconies.\n\nThe building is about twenty years old and well kept, in a strong position by the water.\n\nFlats with a genuine front-line view rather than a partial angle come up rarely in Shengjin.',
      ru: 'Квартира 2+1 в Шенджине на севере Албании, в доме, стоящем на первой линии. Море прямо перед окнами, из зала — прямой вид на воду.\n\nОбщая площадь — 90 м², из них 85 м² по сертификату. Планировка: две отдельные спальни, просторная гостиная и два балкона.\n\nДому около двадцати лет, он ухожен и удачно расположен у воды.\n\nКвартиры с настоящим видом на первую линию, а не «где-то сбоку», в Шенджине появляются редко.',
      uk: 'Квартира 2+1 у Шенджині на півночі Албанії, у будинку, що стоїть на першій лінії. Море просто перед вікнами, із зали — прямий вид на воду.\n\nЗагальна площа — 90 м², з них 85 м² за сертифікатом. Планування: дві окремі спальні, простора вітальня та два балкони.\n\nБудинку близько двадцяти років, він доглянутий і вдало розташований біля води.\n\nКвартири зі справжнім видом на першу лінію, а не «десь збоку», у Шенджині зʼявляються рідко.',
      sq: 'Apartament 2+1 në Shëngjin, në bregdetin verior të Shqipërisë, në një pallat në vijën e parë. Deti është pikërisht para dritareve, me pamje të drejtpërdrejtë nga dhoma e ndenjes.\n\nSipërfaqja e përgjithshme është 90 m², nga të cilat 85 m² sipas certifikatës. Planimetria ofron dy dhoma gjumi më vete, një ndenjë të gjerë dhe dy ballkone.\n\nPallati është rreth njëzet vjeç, i mirëmbajtur dhe në një pozicion të mirë pranë ujit.\n\nApartamente me pamje të vërtetë në vijë të parë, jo anash, dalin rrallë në Shëngjin.',
      it: 'Appartamento 2+1 a Shengjin, sulla costa settentrionale dell’Albania, in un edificio situato in prima linea. Il mare è proprio davanti alle finestre, con vista diretta dal soggiorno.\n\nLa superficie totale è di 90 m², di cui 85 m² da certificato. La distribuzione offre due camere separate, un ampio soggiorno e due balconi.\n\nL’edificio ha circa vent’anni, è curato e in una buona posizione sull’acqua.\n\nAppartamenti con una vera vista in prima linea, e non di scorcio, compaiono raramente a Shengjin.',
      pl: 'Mieszkanie 2+1 w Shengjin, na północnym wybrzeżu Albanii, w budynku stojącym w pierwszej linii. Morze jest wprost przed oknami, z salonu rozciąga się bezpośredni widok.\n\nPowierzchnia całkowita to 90 m², z czego 85 m² według certyfikatu. Układ daje dwie osobne sypialnie, duży salon i dwa balkony.\n\nBudynek ma około dwudziestu lat, jest zadbany i dobrze położony przy wodzie.\n\nMieszkania z prawdziwym widokiem w pierwszej linii, a nie pod kątem, pojawiają się w Shengjin rzadko.',
    },
    address: {
      en: 'Front line, Shengjin',
      ru: 'Первая линия, Шенджин',
      uk: 'Перша лінія, Шенджин',
      sq: 'Vija e parë, Shëngjin',
      it: 'Prima linea, Shengjin',
      pl: 'Pierwsza linia, Shengjin',
    },
    offers: [
      {
        iconKey: 'waves',
        title: {
          en: 'Front line, direct sea view',
          ru: 'Первая линия, прямой вид на море',
          uk: 'Перша лінія, прямий вид на море',
          sq: 'Vijë e parë, pamje e drejtpërdrejtë nga deti',
          it: 'Prima linea, vista mare diretta',
          pl: 'Pierwsza linia, bezpośredni widok na morze',
        },
      },
      {
        iconKey: 'layout',
        title: {
          en: 'Two separate bedrooms, large living room',
          ru: 'Две отдельные спальни, просторная гостиная',
          uk: 'Дві окремі спальні, простора вітальня',
          sq: 'Dy dhoma gjumi më vete, ndenjë e gjerë',
          it: 'Due camere separate, ampio soggiorno',
          pl: 'Dwie osobne sypialnie, duży salon',
        },
      },
      {
        iconKey: 'balcony',
        title: {
          en: 'Two balconies',
          ru: 'Два балкона',
          uk: 'Два балкони',
          sq: 'Dy ballkone',
          it: 'Due balconi',
          pl: 'Dwa balkony',
        },
      },
    ],
    review: 'Partner Telegram and WhatsApp contacts removed from the source text.',
  },

  {
    datoId: 'Ex_3uilVSVSRRNZ86UAH4A',
    slug: 'prodayotsya-kvartira-2-1-2-s-terrasoy-99-m2-i-vidom-na-more-shendzhin',
    city: 'shengjin',
    district: 'center-shengjin',
    type: 'penthouse',
    status: 'sale',
    price: 435200,
    area: 256,
    bedrooms: 2,
    bathrooms: 2,
    title: {
      en: 'Top-Floor Apartment 256 m² with a 99 m² Terrace and Sea View — Shengjin',
      ru: 'Квартира 256 м² на последнем этаже с террасой 99 м² и видом на море — Шенджин',
      uk: 'Квартира 256 м² на останньому поверсі з терасою 99 м² та видом на море — Шенджин',
      sq: 'Apartament 256 m² në katin e fundit me tarracë 99 m² dhe pamje nga deti — Shëngjin',
      it: 'Appartamento all’ultimo piano di 256 m² con terrazza di 99 m² e vista mare — Shengjin',
      pl: 'Mieszkanie 256 m² na ostatnim piętrze z tarasem 99 m² i widokiem na morze — Shengjin',
    },
    shortDescription: {
      en: 'A 256 m² top-floor apartment in Shengjin with a 99 m² terrace, panoramic sea views and room to be reconfigured.',
      ru: 'Квартира 256 м² на последнем этаже в Шенджине с террасой 99 м², панорамным видом на море и возможностью перепланировки.',
      uk: 'Квартира 256 м² на останньому поверсі в Шенджині з терасою 99 м², панорамним видом на море та можливістю перепланування.',
      sq: 'Apartament 256 m² në katin e fundit në Shëngjin me tarracë 99 m², pamje panoramike nga deti dhe mundësi rikonfigurimi.',
      it: 'Appartamento di 256 m² all’ultimo piano a Shengjin con terrazza di 99 m², vista panoramica sul mare e possibilità di riconfigurazione.',
      pl: 'Mieszkanie 256 m² na ostatnim piętrze w Shengjin z tarasem 99 m², panoramicznym widokiem na morze i możliwością przebudowy.',
    },
    description: {
      en: 'A large top-floor apartment in Shengjin, on the northern Albanian coast, with a panoramic sea view and a terrace of 99 m². The total area is 256 m², priced at €1,700 per square metre.\n\nThe current layout is two separate bedrooms, a very large living room and two bathrooms, one of them within a bedroom.\n\nThe size is the point here. It suits a large family as it stands, but it can also be divided so that two households live independently, or reconfigured into several apartments. The terrace is large enough to take a spa area, a hot tub or a lounge.\n\nIt works as a home, as an investment, or as the basis for a premium or boutique letting format.',
      ru: 'Большая квартира на последнем этаже в Шенджине на севере Албании, с панорамным видом на море и террасой 99 м². Общая площадь — 256 м², цена — 1700 € за квадратный метр.\n\nТекущая планировка: две раздельные спальни, очень просторная гостиная и два санузла, один из которых расположен в спальне.\n\nГлавное здесь — метраж. Квартира подходит большой семье как есть, но пространство можно и разделить, чтобы две семьи жили независимо, или перепланировать в несколько апартаментов. Террасы хватает под SPA-зону, джакузи или лаунж.\n\nПодходит и для жизни, и как инвестиция, и как основа для премиального или бутик-формата аренды.',
      uk: 'Велика квартира на останньому поверсі в Шенджині на півночі Албанії, з панорамним видом на море й терасою 99 м². Загальна площа — 256 м², ціна — 1700 € за квадратний метр.\n\nПоточне планування: дві роздільні спальні, дуже простора вітальня та два санвузли, один із яких розташований у спальні.\n\nГоловне тут — метраж. Квартира підходить великій родині як є, але простір можна й розділити, щоб дві сімʼї жили незалежно, або перепланувати на кілька апартаментів. Тераси вистачає під SPA-зону, джакузі чи лаунж.\n\nПідходить і для життя, і як інвестиція, і як основа для преміального або бутик-формату оренди.',
      sq: 'Apartament i madh në katin e fundit në Shëngjin, në bregdetin verior të Shqipërisë, me pamje panoramike nga deti dhe tarracë prej 99 m². Sipërfaqja e përgjithshme është 256 m², me çmim 1.700 € për metër katror.\n\nPlanimetria aktuale: dy dhoma gjumi të ndara, një ndenjë shumë e gjerë dhe dy tualete, njëri prej tyre brenda një dhome gjumi.\n\nPikëforca këtu është sipërfaqja. I përshtatet një familjeje të madhe ashtu siç është, por hapësira mund të ndahet që dy familje të jetojnë veçmas, ose të rikonfigurohet në disa apartamente. Tarraca është aq e madhe sa të presë një zonë spa, një vaskë me hidromasazh ose një lounge.\n\nFunksionon si banesë, si investim, ose si bazë për një format qiraje premium a butik.',
      it: 'Grande appartamento all’ultimo piano a Shengjin, sulla costa settentrionale dell’Albania, con vista panoramica sul mare e una terrazza di 99 m². La superficie totale è di 256 m², al prezzo di 1.700 € al metro quadro.\n\nLa distribuzione attuale prevede due camere separate, un soggiorno molto ampio e due bagni, uno dei quali all’interno di una camera.\n\nQui è la metratura a fare la differenza. Va bene per una famiglia numerosa così com’è, ma lo spazio può anche essere diviso per far vivere due nuclei in modo indipendente, o riconfigurato in più appartamenti. La terrazza è abbastanza grande da ospitare una zona spa, una vasca idromassaggio o un lounge.\n\nFunziona come casa, come investimento o come base per un formato di affitto premium o boutique.',
      pl: 'Duże mieszkanie na ostatnim piętrze w Shengjin, na północnym wybrzeżu Albanii, z panoramicznym widokiem na morze i tarasem o powierzchni 99 m². Powierzchnia całkowita to 256 m², cena 1700 € za metr kwadratowy.\n\nObecny układ: dwie oddzielne sypialnie, bardzo duży salon i dwie łazienki, z których jedna znajduje się w sypialni.\n\nNajważniejszy jest tu metraż. Mieszkanie sprawdzi się dla dużej rodziny w obecnym stanie, ale przestrzeń można też podzielić tak, by dwa gospodarstwa mieszkały niezależnie, albo przebudować na kilka apartamentów. Taras jest na tyle duży, że zmieści strefę spa, jacuzzi lub lounge.\n\nSprawdzi się jako dom, jako inwestycja albo jako baza pod wynajem w formacie premium lub butikowym.',
    },
    address: {
      en: 'Shengjin, northern Albanian coast',
      ru: 'Шенджин, север побережья Албании',
      uk: 'Шенджин, північ узбережжя Албанії',
      sq: 'Shëngjin, bregdeti verior i Shqipërisë',
      it: 'Shengjin, costa settentrionale dell’Albania',
      pl: 'Shengjin, północne wybrzeże Albanii',
    },
    offers: [
      {
        iconKey: 'balcony',
        title: {
          en: 'Terrace of 99 m²',
          ru: 'Терраса 99 м²',
          uk: 'Тераса 99 м²',
          sq: 'Tarracë 99 m²',
          it: 'Terrazza di 99 m²',
          pl: 'Taras 99 m²',
        },
      },
      {
        iconKey: 'waves',
        title: {
          en: 'Top floor, panoramic sea view',
          ru: 'Последний этаж, панорамный вид на море',
          uk: 'Останній поверх, панорамний вид на море',
          sq: 'Kati i fundit, pamje panoramike nga deti',
          it: 'Ultimo piano, vista panoramica sul mare',
          pl: 'Ostatnie piętro, panoramiczny widok na morze',
        },
      },
      {
        iconKey: 'layout',
        title: {
          en: 'Can be divided or reconfigured into several units',
          ru: 'Можно разделить или перепланировать под несколько квартир',
          uk: 'Можна розділити або перепланувати на кілька квартир',
          sq: 'Mund të ndahet ose të rikonfigurohet në disa njësi',
          it: 'Divisibile o riconfigurabile in più unità',
          pl: 'Można podzielić lub przebudować na kilka lokali',
        },
      },
      {
        iconKey: 'home',
        title: {
          en: 'Two bathrooms, one en suite',
          ru: 'Два санузла, один в спальне',
          uk: 'Два санвузли, один у спальні',
          sq: 'Dy tualete, njëri brenda dhomës së gjumit',
          it: 'Due bagni, uno in camera',
          pl: 'Dwie łazienki, jedna przy sypialni',
        },
      },
    ],
    review:
      'Listed as "elite property" in Dato; mapped to the penthouse type since it is a top-floor flat with a large terrace. Confirm if villa or apartment fits better.',
  },

  {
    datoId: 'FvIaya6BQQ2DAAGiIDa3PA',
    slug: 'prodaetsya-prostornaya-stilnaya-studii',
    city: 'durres',
    district: 'plazh',
    type: 'studio',
    status: 'sale',
    price: 77000,
    area: 47,
    bedrooms: 1,
    bathrooms: 1,
    title: {
      en: 'Spacious Studio 47 m² in the Tocak Complex — Plazh, Durres',
      ru: 'Просторная студия 47 м² в комплексе Tocak — Пляж, Дуррес',
      uk: 'Простора студія 47 м² у комплексі Tocak — Пляж, Дуррес',
      sq: 'Studio e gjerë 47 m² në kompleksin Tocak — Plazh, Durrës',
      it: 'Ampio monolocale di 47 m² nel complesso Tocak — Plazh, Durazzo',
      pl: 'Przestronna kawalerka 47 m² w kompleksie Tocak — Plazh, Durres',
    },
    shortDescription: {
      en: 'A 47 m² studio in the Tocak complex with guarded private parking, 350 metres from the sea, with new furniture and appliances.',
      ru: 'Студия 47 м² в комплексе Tocak с охраняемой частной парковкой, в 350 метрах от моря, с новой мебелью и техникой.',
      uk: 'Студія 47 м² у комплексі Tocak з охоронюваною приватною парковкою, за 350 метрів від моря, з новими меблями й технікою.',
      sq: 'Studio 47 m² në kompleksin Tocak me parking privat të ruajtur, 350 metra nga deti, me mobilie dhe pajisje të reja.',
      it: 'Monolocale di 47 m² nel complesso Tocak con parcheggio privato custodito, a 350 metri dal mare, con mobili ed elettrodomestici nuovi.',
      pl: 'Kawalerka 47 m² w kompleksie Tocak ze strzeżonym prywatnym parkingiem, 350 metrów od morza, z nowymi meblami i sprzętem.',
    },
    description: {
      en: 'A 47 m² studio on the second floor of the Tocak complex in Plazh, Durres, with guarded private parking on the grounds. The sea is 350 metres away.\n\nThe furniture and appliances are new and the flat is in excellent condition, so it can be lived in or let immediately.\n\nEverything around it runs all year: supermarkets, cafés, exchange offices, pharmacies, shops and the promenade. A bus stop is 200 metres away, with a minibus to the centre every twenty minutes.',
      ru: 'Студия 47 м² на втором этаже комплекса Tocak в районе Пляж, Дуррес, с охраняемой частной парковкой на территории. До моря 350 метров.\n\nМебель и техника новые, состояние отличное — можно сразу жить или сдавать.\n\nВсё вокруг работает круглый год: супермаркеты, кафе, обменные пункты, аптеки, магазины и набережная. Остановка в 200 метрах, маршрутка до центра каждые двадцать минут.',
      uk: 'Студія 47 м² на другому поверсі комплексу Tocak у районі Пляж, Дуррес, з охоронюваною приватною парковкою на території. До моря 350 метрів.\n\nМеблі й техніка нові, стан відмінний — можна одразу жити або здавати.\n\nУсе навколо працює цілий рік: супермаркети, кафе, обмінні пункти, аптеки, магазини й набережна. Зупинка за 200 метрів, маршрутка до центру кожні двадцять хвилин.',
      sq: 'Studio 47 m² në katin e dytë të kompleksit Tocak në Plazh, Durrës, me parking privat të ruajtur brenda territorit. Deti është 350 metra larg.\n\nMobiliet dhe pajisjet janë të reja dhe gjendja është shumë e mirë, prandaj mund të banohet ose të jepet me qira menjëherë.\n\nGjithçka përreth punon gjatë gjithë vitit: supermarkete, kafene, këmbimore, farmaci, dyqane dhe shëtitorja. Stacioni i autobusit është 200 metra larg, me furgon drejt qendrës çdo njëzet minuta.',
      it: 'Monolocale di 47 m² al secondo piano del complesso Tocak a Plazh, Durazzo, con parcheggio privato custodito all’interno. Il mare dista 350 metri.\n\nMobili ed elettrodomestici sono nuovi e le condizioni ottime, quindi si può abitare o affittare da subito.\n\nTutto intorno è attivo tutto l’anno: supermercati, bar, uffici di cambio, farmacie, negozi e il lungomare. La fermata dell’autobus è a 200 metri, con minibus per il centro ogni venti minuti.',
      pl: 'Kawalerka o powierzchni 47 m² na drugim piętrze kompleksu Tocak w Plazh, Durres, ze strzeżonym prywatnym parkingiem na terenie. Do morza 350 metrów.\n\nMeble i sprzęt są nowe, stan bardzo dobry, więc można od razu zamieszkać lub wynajmować.\n\nWszystko wokół działa przez cały rok: supermarkety, kawiarnie, kantory, apteki, sklepy i promenada. Przystanek jest 200 metrów dalej, a minibus do centrum kursuje co dwadzieścia minut.',
    },
    address: {
      en: 'Tocak complex, Plazh, Durres',
      ru: 'Комплекс Tocak, район Пляж, Дуррес',
      uk: 'Комплекс Tocak, район Пляж, Дуррес',
      sq: 'Kompleksi Tocak, Plazh, Durrës',
      it: 'Complesso Tocak, Plazh, Durazzo',
      pl: 'Kompleks Tocak, Plazh, Durres',
    },
    offers: [
      {
        iconKey: 'shield',
        title: {
          en: 'Guarded private parking on site',
          ru: 'Охраняемая частная парковка на территории',
          uk: 'Охоронювана приватна парковка на території',
          sq: 'Parking privat i ruajtur brenda territorit',
          it: 'Parcheggio privato custodito interno',
          pl: 'Strzeżony prywatny parking na terenie',
        },
      },
      {
        iconKey: 'waves',
        title: {
          en: '350 m from the sea',
          ru: '350 м до моря',
          uk: '350 м до моря',
          sq: '350 m nga deti',
          it: '350 m dal mare',
          pl: '350 m od morza',
        },
      },
      {
        iconKey: 'sofa',
        title: {
          en: 'New furniture and appliances',
          ru: 'Новая мебель и техника',
          uk: 'Нові меблі й техніка',
          sq: 'Mobilie dhe pajisje të reja',
          it: 'Mobili ed elettrodomestici nuovi',
          pl: 'Nowe meble i sprzęt',
        },
      },
      {
        iconKey: 'car',
        title: {
          en: 'Bus stop 200 m away, minibus to the centre every 20 min',
          ru: 'Остановка в 200 м, маршрутка до центра каждые 20 минут',
          uk: 'Зупинка за 200 м, маршрутка до центру кожні 20 хвилин',
          sq: 'Stacioni 200 m larg, furgon drejt qendrës çdo 20 minuta',
          it: 'Fermata a 200 m, minibus per il centro ogni 20 minuti',
          pl: 'Przystanek 200 m, minibus do centrum co 20 minut',
        },
      },
    ],
  },
]
