import type { L } from './fixContentQa2026.data';

/**
 * Tirana district descriptions (localizedText), 400+ chars each, sourced from
 * knowledge-base/03-districts/tirana-districts.md. Prices carry cautious "2026"
 * framing. `dajti` is not in the knowledge base → minimal honest text, no
 * invented facts. `new-bazaar` is a duplicate of `pazari-i-ri` and is
 * unpublished, so it gets no description here.
 */
export const DISTRICT_DESCRIPTIONS: Record<string, L> = {
  blloku: {
    en: 'Blloku (Ish-Blloku) is the former closed party quarter, today the epicentre of Tirana’s bars, boutiques and offices. It is the most prestigious and most walkable central district, popular with the local elite, buy-to-let investors and foreign buyers. As of 2026, new builds trade around €3,000–5,500/m² and resale around €2,500–3,500/m², among the highest in the city. The upside is prestige, safety and liquidity; the trade-offs are noise, traffic and tight parking. Blloku suits buyers who value capital preservation and status over maximum rental yield.',
    ru: 'Блоку (Ish-Blloku) — бывший закрытый партийный квартал, сегодня эпицентр баров, бутиков и офисов Тираны. Это самый престижный и удобный для пешеходов центральный район, популярный у местной элиты, инвесторов под аренду и иностранных покупателей. По данным на 2026 год, новостройки — около €3 000–5 500/м², вторичка — около €2 500–3 500/м², одни из самых высоких в городе. Плюсы — престиж, безопасность и ликвидность; минусы — шум, трафик и дефицит парковки. Блоку подходит тем, кто ценит сохранение капитала и статус больше максимальной доходности.',
    uk: 'Блоку (Ish-Blloku) — колишній закритий партійний квартал, сьогодні епіцентр барів, бутиків та офісів Тирани. Це найпрестижніший і найзручніший для пішоходів центральний район, популярний серед місцевої еліти, інвесторів під оренду та іноземних покупців. За даними на 2026 рік, новобудови — близько €3 000–5 500/м², вторинка — близько €2 500–3 500/м², одні з найвищих у місті. Плюси — престиж, безпека та ліквідність; мінуси — шум, трафік і дефіцит паркування. Блоку підходить тим, хто цінує збереження капіталу та статус більше за максимальну дохідність.',
    sq: 'Blloku (Ish-Blloku) është ish-lagja e mbyllur e partisë, sot epiqendra e bareve, butikëve dhe zyrave të Tiranës. Është lagjja qendrore më prestigjioze dhe më e përshtatshme për këmbësorë, e preferuar nga elita vendase, investitorët për qira dhe blerësit e huaj. Sipas të dhënave për vitin 2026, ndërtimet e reja tregtohen rreth 3.000–5.500 €/m² dhe të përdorurat rreth 2.500–3.500 €/m², ndër më të lartat në qytet. Përparësitë janë prestigji, siguria dhe likuiditeti; kompromiset janë zhurma, trafiku dhe parkimi i ngushtë. Blloku u përshtatet blerësve që vlerësojnë ruajtjen e kapitalit dhe statusin më shumë se rendimentin maksimal.',
    it: 'Blloku (Ish-Blloku) è l’ex quartiere chiuso del partito, oggi epicentro di bar, boutique e uffici di Tirana. È il quartiere centrale più prestigioso e pedonale, apprezzato dall’élite locale, dagli investitori buy-to-let e dagli acquirenti stranieri. Nel 2026 il nuovo si aggira sui 3.000–5.500 €/m² e l’usato sui 2.500–3.500 €/m², tra i più alti della città. I vantaggi sono prestigio, sicurezza e liquidità; i compromessi sono rumore, traffico e parcheggio scarso. Blloku è adatto a chi valorizza la conservazione del capitale e lo status più del rendimento massimo.',
  },
  'komuna-e-parisit': {
    en: 'Komuna e Parisit is an upscale, quiet district next to the Grand Park, favoured by embassies, families and expats. It offers a family-oriented prime address without the noise of Blloku. As of 2026, off-plan units start around €3,000/m² near the Civil Aviation building, with completed stock around €2,700/m² (for example Haxhi Kika and the “White Tower”, up about 17% from their 2023 off-plan price). The main drawback is parking. It suits buyers looking for a calm, green, long-hold family home close to the centre with steady resale demand.',
    ru: 'Komuna e Parisit — престижный тихий район у Большого парка, который выбирают посольства, семьи и экспаты. Это семейный прайм без шума Блоку. По данным на 2026 год, котлован стартует около €3 000/м² рядом со зданием Гражданской авиации, готовое — около €2 700/м² (например Haxhi Kika и «White Tower», +17% к цене котлована 2023 года). Основной минус — парковка. Район подходит тем, кто ищет спокойное, зелёное семейное жильё в долгую близко к центру с устойчивым спросом на вторичном рынке.',
    uk: 'Komuna e Parisit — престижний тихий район біля Великого парку, який обирають посольства, родини та експати. Це сімейний прайм без шуму Блоку. За даними на 2026 рік, котлован стартує близько €3 000/м² поруч із будівлею Цивільної авіації, готове — близько €2 700/м² (наприклад Haxhi Kika та «White Tower», +17% до ціни котловану 2023 року). Основний мінус — паркування. Район підходить тим, хто шукає спокійне, зелене сімейне житло надовго близько до центру зі стабільним попитом на вторинному ринку.',
    sq: 'Komuna e Parisit është një lagje e qetë dhe elitare pranë Parkut të Madh, e preferuar nga ambasadat, familjet dhe të huajt. Ofron një adresë prime familjare pa zhurmën e Bllokut. Sipas të dhënave për 2026, njësitë në fazë projekti nisin rreth 3.000 €/m² pranë ndërtesës së Aviacionit Civil, ndërsa të përfunduarat rreth 2.700 €/m² (për shembull Haxhi Kika dhe “White Tower”, rreth 17% më lart se çmimi i projektit në 2023). Mangësia kryesore është parkimi. I përshtatet blerësve që kërkojnë një shtëpi familjare të qetë e të gjelbër afër qendrës, me kërkesë të qëndrueshme rishitjeje.',
    it: 'Komuna e Parisit è un quartiere tranquillo ed elegante accanto al Grande Parco, prediletto da ambasciate, famiglie ed espatriati. Offre un indirizzo prime familiare senza il rumore di Blloku. Nel 2026 le unità su carta partono da circa 3.000 €/m² vicino all’edificio dell’Aviazione Civile, mentre il costruito è intorno ai 2.700 €/m² (ad esempio Haxhi Kika e la “White Tower”, circa +17% rispetto al prezzo su carta del 2023). Lo svantaggio principale è il parcheggio. È adatto a chi cerca una casa familiare calma e verde vicino al centro, con domanda di rivendita costante.',
  },
  'qender-tirana': {
    en: 'Qendra — the centre around Skanderbeg Square — mixes older stock with new projects near the square. As of 2026, older apartments trade around €1,500–2,500/m² while new developments by the square reach €3,000–3,500/m²; inside the Small Ring, new builds start around €2,300/m². The centre offers unbeatable access to institutions, culture and transport, and strong short-stay demand. The trade-offs are noise, a mix of building ages and tourist bustle. It suits buyers who want a central, liquid address and accept a heterogeneous housing stock.',
    ru: 'Qendra — центр вокруг площади Скандербега — сочетает старый фонд с новыми проектами у площади. По данным на 2026 год, старые квартиры — около €1 500–2 500/м², новые проекты у площади — €3 000–3 500/м²; внутри Малого кольца новостройки стартуют около €2 300/м². Центр даёт непревзойдённый доступ к институтам, культуре и транспорту и высокий спрос на короткое проживание. Минусы — шум, разнородный по возрасту фонд и туристическая суета. Подходит тем, кому нужен центральный ликвидный адрес при готовности к неоднородному фонду.',
    uk: 'Qendra — центр навколо площі Скандербега — поєднує старий фонд із новими проєктами біля площі. За даними на 2026 рік, старі квартири — близько €1 500–2 500/м², нові проєкти біля площі — €3 000–3 500/м²; усередині Малого кільця новобудови стартують близько €2 300/м². Центр дає неперевершений доступ до інституцій, культури й транспорту та високий попит на коротке проживання. Мінуси — шум, різнорідний за віком фонд і туристична метушня. Підходить тим, кому потрібна центральна ліквідна адреса за готовності до неоднорідного фонду.',
    sq: 'Qendra — zona rreth Sheshit Skënderbej — ndërthur fondin e vjetër me projekte të reja pranë sheshit. Sipas të dhënave për 2026, apartamentet e vjetra tregtohen rreth 1.500–2.500 €/m², ndërsa zhvillimet e reja pranë sheshit arrijnë 3.000–3.500 €/m²; brenda Unazës së Vogël, ndërtimet e reja nisin rreth 2.300 €/m². Qendra ofron akses të pashoq te institucionet, kultura dhe transporti, si dhe kërkesë të fortë për qëndrime të shkurtra. Kompromiset janë zhurma, mosha e larmishme e ndërtesave dhe zhurma turistike. I përshtatet blerësve që duan një adresë qendrore e likuide dhe pranojnë një fond banesash heterogjen.',
    it: 'Qendra — il centro attorno a Piazza Skanderbeg — mescola edilizia più vecchia a nuovi progetti vicino alla piazza. Nel 2026 gli appartamenti vecchi si aggirano sui 1.500–2.500 €/m², mentre i nuovi sviluppi presso la piazza raggiungono 3.000–3.500 €/m²; entro l’Anello Piccolo, il nuovo parte da circa 2.300 €/m². Il centro offre un accesso impareggiabile a istituzioni, cultura e trasporti, e forte domanda di soggiorni brevi. I compromessi sono rumore, edifici di età diverse e viavai turistico. È adatto a chi vuole un indirizzo centrale e liquido e accetta un parco immobiliare eterogeneo.',
  },
  'pazari-i-ri': {
    en: 'Pazari i Ri (the New Bazaar), renovated in 2016, is Tirana’s revived market quarter within the central Qendra area and one of the city’s best short-stay locations. Restaurants, cafés and the covered market draw steady tourist footfall, which supports strong holiday-rental demand. Housing here is part of the wider centre: older stock and new projects sit side by side, with 2026 prices broadly in line with the central market — from around €2,300/m² for new builds, higher near the square. The trade-offs are noise and tourist bustle; the appeal is character, walkability and rental potential.',
    ru: 'Pazari i Ri (Новый базар), реновированный в 2016 году, — возрождённый рыночный квартал в составе центральной зоны Qendra и одно из лучших мест города для короткого проживания. Рестораны, кафе и крытый рынок дают устойчивый турпоток, поддерживающий высокий спрос на посуточную аренду. Жильё здесь — часть общего центра: старый фонд и новые проекты соседствуют, цены 2026 года в целом на уровне центрального рынка — от около €2 300/м² за новостройки, дороже у площади. Минусы — шум и туристическая суета; плюсы — характер, пешеходность и арендный потенциал.',
    uk: 'Pazari i Ri (Новий базар), реновований у 2016 році, — відроджений ринковий квартал у складі центральної зони Qendra й одне з найкращих місць міста для короткого проживання. Ресторани, кафе та критий ринок дають стабільний турпотік, що підтримує високий попит на подобову оренду. Житло тут — частина загального центру: старий фонд і нові проєкти сусідять, ціни 2026 року загалом на рівні центрального ринку — від близько €2 300/м² за новобудови, дорожче біля площі. Мінуси — шум і туристична метушня; плюси — характер, пішохідність та орендний потенціал.',
    sq: 'Pazari i Ri, i rinovuar në vitin 2016, është lagjja e ringjallur e tregut brenda zonës qendrore Qendra dhe një nga vendet më të mira të qytetit për qëndrime të shkurtra. Restorantet, kafenetë dhe tregu i mbuluar tërheqin fluks të qëndrueshëm turistësh, çka mbështet kërkesë të fortë për qira pushimesh. Banesat këtu janë pjesë e qendrës së gjerë: fondi i vjetër dhe projektet e reja qëndrojnë krah për krah, me çmime 2026 gjerësisht në linjë me tregun qendror — nga rreth 2.300 €/m² për ndërtime të reja, më lart pranë sheshit. Kompromiset janë zhurma dhe zhurma turistike; tërheqja është karakteri, ecja në këmbë dhe potenciali i qirasë.',
    it: 'Pazari i Ri (il Nuovo Bazar), ristrutturato nel 2016, è il quartiere-mercato rinato all’interno dell’area centrale Qendra e una delle migliori zone della città per soggiorni brevi. Ristoranti, caffè e il mercato coperto attirano un flusso turistico costante, che sostiene una forte domanda di affitti vacanze. Le abitazioni qui fanno parte del centro più ampio: vecchio e nuovo convivono, con prezzi 2026 in linea con il mercato centrale — da circa 2.300 €/m² per il nuovo, di più vicino alla piazza. I compromessi sono rumore e viavai turistico; il fascino è carattere, pedonabilità e potenziale di locazione.',
  },
  dajti: {
    en: 'Dajti sits on the eastern edge of Tirana, at the foot of Mount Dajti and its national park, reached from the city by the Dajti Ekspres cable car. It is valued for green surroundings, cooler air and mountain views rather than for central-city convenience, and appeals to buyers who prioritise nature and quiet over walkable urban amenities. Because reliable market data for this area is limited, we do not quote specific prices here; ask our team for current listings and an honest assessment before you decide.',
    ru: 'Dajti расположен на восточной окраине Тираны, у подножия горы Дайти и её национального парка, куда из города ведёт канатная дорога Dajti Ekspres. Район ценят за зелёное окружение, более прохладный воздух и горные виды, а не за близость к центру; он подходит тем, для кого природа и тишина важнее пешеходной городской инфраструктуры. Поскольку надёжных рыночных данных по этой зоне мало, мы не приводим здесь конкретных цен; запросите у нашей команды актуальные объекты и честную оценку перед решением.',
    uk: 'Dajti розташований на східній околиці Тирани, біля підніжжя гори Дайті та її національного парку, куди з міста веде канатна дорога Dajti Ekspres. Район цінують за зелене оточення, прохолодніше повітря та гірські краєвиди, а не за близькість до центру; він підходить тим, для кого природа й тиша важливіші за пішохідну міську інфраструктуру. Оскільки надійних ринкових даних щодо цієї зони мало, ми не наводимо тут конкретних цін; запитайте в нашої команди актуальні об’єкти й чесну оцінку перед рішенням.',
    sq: 'Dajti ndodhet në skajin lindor të Tiranës, në këmbë të malit të Dajtit dhe parkut të tij kombëtar, ku arrihet nga qyteti me teleferikun Dajti Ekspres. Vlerësohet për mjedisin e gjelbër, ajrin më të freskët dhe pamjet malore, jo për afërsinë me qendrën; u përshtatet blerësve që vënë natyrën dhe qetësinë përpara lehtësive urbane. Meqë të dhënat e besueshme të tregut për këtë zonë janë të kufizuara, nuk citojmë çmime specifike këtu; kërkoni nga ekipi ynë listimet aktuale dhe një vlerësim të ndershëm përpara se të vendosni.',
    it: 'Dajti si trova sul margine orientale di Tirana, ai piedi del monte Dajti e del suo parco nazionale, raggiungibile dalla città con la funivia Dajti Ekspres. È apprezzato per il verde, l’aria più fresca e le viste sulle montagne, più che per la vicinanza al centro; attrae chi mette natura e quiete davanti ai servizi urbani a portata di piede. Poiché i dati di mercato affidabili per questa zona sono limitati, qui non indichiamo prezzi specifici; chiedi al nostro team gli annunci attuali e una valutazione onesta prima di decidere.',
  },
};
