/**
 * Sanity query layer — single entry point for frontend.
 *
 * Export queries and fragments for use in next-sanity client.
 */

// Queries
export {
  HOME_PAGE_QUERY,
  LANDING_PAGE_BY_SLUG_QUERY,
  CITY_LANDING_BY_CITY_SLUG_QUERY,
  SITE_SETTINGS_QUERY,
  CITIES_LIST_QUERY,
  CITY_PAGE_QUERY,
  DISTRICT_PAGE_QUERY,
  PROPERTY_TYPES_QUERY,
  LOCATION_TAGS_QUERY,
  AMENITIES_QUERY,
  PROPERTIES_LIST_QUERY,
  PROPERTY_BY_SLUG_QUERY,
  BLOG_POSTS_QUERY,
  BLOG_POST_BY_SLUG_QUERY,
  BLOG_CATEGORIES_QUERY,
  POPULAR_CITIES_QUERY,
  FEATURED_PROPERTIES_QUERY,
} from './queries'

// groq (for custom query composition)
export {groq} from './fragments'

// Fragments (for custom query composition)
export {
  LOCALIZED_TITLE_FRAGMENT,
  LOCALIZED_TEXT_FRAGMENT,
  LOCALIZED_SLUG_FRAGMENT,
  IMAGE_FRAGMENT,
  GALLERY_FRAGMENT,
  LOCALIZED_SEO_FRAGMENT,
  LOCALIZED_CTA_LINK_FRAGMENT,
  LOCALIZED_FOOTER_LINK_FRAGMENT,
  SOCIAL_LINK_FRAGMENT,
  CITY_CARD_FRAGMENT,
  DISTRICT_CARD_FRAGMENT,
  CITY_REF_FRAGMENT,
  DISTRICT_REF_FRAGMENT,
  PROPERTY_TYPE_FRAGMENT,
  PROPERTY_TYPE_REF_FRAGMENT,
  PROPERTY_TYPE_FULL_REF_FRAGMENT,
  LOCATION_TAG_FRAGMENT,
  LOCATION_TAG_REF_FRAGMENT,
  AMENITY_FRAGMENT,
  PROPERTY_CARD_FRAGMENT,
  PROPERTY_FULL_FRAGMENT,
  BLOG_CATEGORY_FRAGMENT,
  BLOG_CATEGORY_REF_FRAGMENT,
  BLOG_POST_CARD_FRAGMENT,
  BLOG_POST_FULL_FRAGMENT,
} from './fragments'
